const fs = require("fs");
const pptx = require("pptxgenjs");

const ppt_doc_1 = new pptx();
const ppt_doc_1_debug = { defaultStyle: {}, styles: {}, slides: [] };
const defaultStyle = { content: {} };
const styles = {};
const ppt_defaultStyleDef_2 = {};
ppt_defaultStyleDef_2.fontFace = "Tahoma";
ppt_defaultStyleDef_2.fontSize = 12;
ppt_defaultStyleDef_2.valign = "middle";
defaultStyle.content = ppt_defaultStyleDef_2;
ppt_doc_1_debug.defaultStyle = ppt_defaultStyleDef_2;
const ppt_styleDef_3 = {};
ppt_styleDef_3.fontSize = 52;
ppt_styleDef_3.x = "30%";
ppt_styleDef_3.w ="60%";
ppt_styleDef_3.bold = true;
styles[".forefront-title"] = ppt_styleDef_3;
ppt_doc_1_debug.styles[".forefront-title"] = ppt_styleDef_3;
const ppt_styleDef_4 = {};
ppt_styleDef_4.fontSize = 36;
ppt_styleDef_4.x = "30%";
ppt_styleDef_4.w ="60%";
ppt_styleDef_4.italic = true;
styles[".forefront-subtitle"] = ppt_styleDef_4;
ppt_doc_1_debug.styles[".forefront-subtitle"] = ppt_styleDef_4;
const ppt_styleDef_5 = {};
ppt_styleDef_5.fontSize = 13.5;
ppt_styleDef_5.x = "30%";
ppt_styleDef_5.w ="60%";
styles[".forefront-author"] = ppt_styleDef_5;
ppt_doc_1_debug.styles[".forefront-author"] = ppt_styleDef_5;
const ppt_styleDef_6 = {};
ppt_styleDef_6.fontSize = 9;
ppt_styleDef_6.x = "30%";
ppt_styleDef_6.w ="60%";
ppt_styleDef_6.italic = true;
styles[".forefront-date"] = ppt_styleDef_6;
ppt_doc_1_debug.styles[".forefront-date"] = ppt_styleDef_6;
const ppt_styleDef_7 = {};
ppt_styleDef_7.fontSize = 32;
ppt_styleDef_7.x = "30%";
ppt_styleDef_7.y = "8%";
ppt_styleDef_7.w ="70%";
ppt_styleDef_7.x = "20%";
ppt_styleDef_7.bold = true;
ppt_styleDef_7.color = "#e02424";
ppt_styleDef_7.align = "right";
styles["titolo1"] = ppt_styleDef_7;
ppt_doc_1_debug.styles["titolo1"] = ppt_styleDef_7;
const ppt_styleDef_8 = {};
ppt_styleDef_8.fontSize = 21;
ppt_styleDef_8.x = "10%";
ppt_styleDef_8.y = "12%";
ppt_styleDef_8.w ="80%";
ppt_styleDef_8.x = "8%";
ppt_styleDef_8.bold = true;
ppt_styleDef_8.italic = true;
ppt_styleDef_8.color = "#020202";
ppt_styleDef_8.align = "left";
styles["titolo2"] = ppt_styleDef_8;
ppt_doc_1_debug.styles["titolo2"] = ppt_styleDef_8;
const ppt_styleDef_9 = {};
ppt_styleDef_9.fontSize = 15;
ppt_styleDef_9.align = "left";
styles["para1"] = ppt_styleDef_9;
ppt_doc_1_debug.styles["para1"] = ppt_styleDef_9;
const ppt_styleDef_10 = {};
ppt_styleDef_10.fontSize = 37.5;
ppt_styleDef_10.align = "left";
ppt_styleDef_10.x = "20%";
styles["para1big"] = ppt_styleDef_10;
ppt_doc_1_debug.styles["para1big"] = ppt_styleDef_10;
const ppt_styleDef_11 = {};
styles[".cite-reviews"] = ppt_styleDef_11;
ppt_doc_1_debug.styles[".cite-reviews"] = ppt_styleDef_11;
const ppt_styleDef_12 = {};
ppt_styleDef_12.fontSize = 10;
ppt_styleDef_12.align = "left";
ppt_styleDef_12.x = "20%";
ppt_styleDef_12.bold = true;
styles[".cite-article"] = ppt_styleDef_12;
ppt_doc_1_debug.styles[".cite-article"] = ppt_styleDef_12;
const ppt_styleDef_13 = {};
ppt_styleDef_13.fontSize = 10;
ppt_styleDef_13.italic = true;
ppt_styleDef_13.align = "left";
ppt_styleDef_13.x = "20%";
styles[".cite-authors"] = ppt_styleDef_13;
ppt_doc_1_debug.styles[".cite-authors"] = ppt_styleDef_13;
const ppt_styleDef_14 = {};
ppt_styleDef_14.fontSize = 10;
ppt_styleDef_14.italic = true;
ppt_styleDef_14.align = "left";
styles[".cite-review"] = ppt_styleDef_14;
ppt_doc_1_debug.styles[".cite-review"] = ppt_styleDef_14;
const ppt_styleDef_15 = {};
ppt_styleDef_15.fontSize = 60;
ppt_styleDef_15.align = "center";
ppt_styleDef_15.color = "#e02424";
ppt_styleDef_15.bold = true;
ppt_styleDef_15.x = "20%";
ppt_styleDef_15.w ="60%";
styles[".thanks-title"] = ppt_styleDef_15;
ppt_doc_1_debug.styles[".thanks-title"] = ppt_styleDef_15;
const ppt_styleDef_16 = {};
ppt_styleDef_16.fontSize = 48;
ppt_styleDef_16.align = "center";
ppt_styleDef_16.color = "#e02424";
ppt_styleDef_16.bold = true;
ppt_styleDef_16.x = "20%";
ppt_styleDef_16.w ="60%";
styles[".thanks-subtitle"] = ppt_styleDef_16;
ppt_doc_1_debug.styles[".thanks-subtitle"] = ppt_styleDef_16;
const ppt_styleDef_17 = {};
ppt_styleDef_17.fontSize = 16;
ppt_styleDef_17.bold = true;
styles[".column-title"] = ppt_styleDef_17;
ppt_doc_1_debug.styles[".column-title"] = ppt_styleDef_17;
const ppt_styleDef_18 = {};
ppt_styleDef_18.fontSize = 14;
styles[".column-p"] = ppt_styleDef_18;
ppt_doc_1_debug.styles[".column-p"] = ppt_styleDef_18;
const ppt_styleDef_19 = {};
ppt_styleDef_19.fontSize = 28;
styles[".column-p-big"] = ppt_styleDef_19;
ppt_doc_1_debug.styles[".column-p-big"] = ppt_styleDef_19;
const ppt_slide_20 = ppt_doc_1.addSlide();
const ppt_slide_20_debug = { items: [] };
var ppt_p_21 = Object.assign({}, defaultStyle.content);
const ppt_p_21_text = "Le guide anticipatorie";
ppt_p_21 = Object.assign({},ppt_p_21, (styles[".forefront-title"] || {}));
ppt_p_21.y = "25%";
ppt_p_21.isTextBox = true;
ppt_slide_20.addText(ppt_p_21_text, ppt_p_21);
ppt_slide_20_debug.items.push({ text: ppt_p_21_text, options: ppt_p_21 });
var ppt_p_22 = Object.assign({}, defaultStyle.content);
const ppt_p_22_text = "Tutti a tavola";
ppt_p_22 = Object.assign({},ppt_p_22, (styles[".forefront-subtitle"] || {}));
ppt_p_22.y = "52%";
ppt_p_22.isTextBox = true;
ppt_slide_20.addText(ppt_p_22_text, ppt_p_22);
ppt_slide_20_debug.items.push({ text: ppt_p_22_text, options: ppt_p_22 });
var ppt_p_23 = Object.assign({}, defaultStyle.content);
const ppt_p_23_text = "Nati per leggere";
ppt_p_23 = Object.assign({},ppt_p_23, (styles[".forefront-subtitle"] || {}));
ppt_p_23.y = "67%";
ppt_p_23.isTextBox = true;
ppt_slide_20.addText(ppt_p_23_text, ppt_p_23);
ppt_slide_20_debug.items.push({ text: ppt_p_23_text, options: ppt_p_23 });
var ppt_p_24 = Object.assign({}, defaultStyle.content);
const ppt_p_24_text = "Anna Maria Davoli";
ppt_p_24 = Object.assign({},ppt_p_24, (styles[".forefront-author"] || {}));
ppt_p_24.y = "80%";
ppt_p_24.isTextBox = true;
ppt_slide_20.addText(ppt_p_24_text, ppt_p_24);
ppt_slide_20_debug.items.push({ text: ppt_p_24_text, options: ppt_p_24 });
var ppt_p_25 = Object.assign({}, defaultStyle.content);
const ppt_p_25_text = "17 marzo 2021";
ppt_p_25 = Object.assign({},ppt_p_25, (styles[".forefront-date"] || {}));
ppt_p_25.y = "85%";
ppt_p_25.isTextBox = true;
ppt_slide_20.addText(ppt_p_25_text, ppt_p_25);
ppt_slide_20_debug.items.push({ text: ppt_p_25_text, options: ppt_p_25 });
const ppt_image_26 = {};
ppt_image_26.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/cosie.jpg";
ppt_image_26.x = "6%";
ppt_image_26.y = "24%";
ppt_image_26.w ="16%";
ppt_image_26.h ="16%";
ppt_slide_20.addImage(ppt_image_26);
ppt_slide_20_debug.items.push({ image: ppt_image_26 });
const ppt_image_27 = {};
ppt_image_27.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/bminforma.png";
ppt_image_27.x = "6%";
ppt_image_27.y = "42%";
ppt_image_27.w ="16%";
ppt_image_27.h ="16%";
ppt_slide_20.addImage(ppt_image_27);
ppt_slide_20_debug.items.push({ image: ppt_image_27 });
const ppt_image_28 = {};
ppt_image_28.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/npl.jpg";
ppt_image_28.x = "6%";
ppt_image_28.y = "60%";
ppt_image_28.w ="16%";
ppt_image_28.h ="16%";
ppt_slide_20.addImage(ppt_image_28);
ppt_slide_20_debug.items.push({ image: ppt_image_28 });
ppt_doc_1_debug.slides.push(ppt_slide_20_debug);
const ppt_slide_29 = ppt_doc_1.addSlide();
const ppt_slide_29_debug = { items: [] };
var ppt_p_30 = Object.assign({}, defaultStyle.content);
const ppt_p_30_text = "";
ppt_p_30 = Object.assign({},ppt_p_30, (styles["titolo1"] || {}));
ppt_p_30.isTextBox = true;
ppt_slide_29.addText(ppt_p_30_text, ppt_p_30);
ppt_slide_29_debug.items.push({ text: ppt_p_30_text, options: ppt_p_30 });
var ppt_p_31 = Object.assign({}, defaultStyle.content);
const ppt_p_31_text = "Le App a supporto di genitori e caregiver";
ppt_p_31 = Object.assign({},ppt_p_31, (styles["titolo2"] || {}));
ppt_p_31.isTextBox = true;
ppt_slide_29.addText(ppt_p_31_text, ppt_p_31);
ppt_slide_29_debug.items.push({ text: ppt_p_31_text, options: ppt_p_31 });
var ppt_p_32 = Object.assign({}, defaultStyle.content);
const ppt_p_32_text = "Contenuti basati sulle evidenze";
ppt_p_32 = Object.assign({},ppt_p_32, (styles["para1"] || {}));
ppt_p_32.bullet = true;
ppt_p_32.color = "FF0000";
ppt_p_32.x = "10%";
ppt_p_32.y = "24%";
ppt_p_32.w ="80%";
ppt_p_32.isTextBox = true;
ppt_slide_29.addText(ppt_p_32_text, ppt_p_32);
ppt_slide_29_debug.items.push({ text: ppt_p_32_text, options: ppt_p_32 });
var ppt_p_33 = Object.assign({}, defaultStyle.content);
const ppt_p_33_text = "Informazioni coerenti con le linee guida";
ppt_p_33 = Object.assign({},ppt_p_33, (styles["para1"] || {}));
ppt_p_33.bullet = true;
ppt_p_33.color = "FF0000";
ppt_p_33.x = "10%";
ppt_p_33.y = "34%";
ppt_p_33.w ="80%";
ppt_p_33.isTextBox = true;
ppt_slide_29.addText(ppt_p_33_text, ppt_p_33);
ppt_slide_29_debug.items.push({ text: ppt_p_33_text, options: ppt_p_33 });
var ppt_p_34 = Object.assign({}, defaultStyle.content);
const ppt_p_34_text = "Sviluppate con il supporto di professionisti sanitari";
ppt_p_34 = Object.assign({},ppt_p_34, (styles["para1"] || {}));
ppt_p_34.bullet = true;
ppt_p_34.color = "FF0000";
ppt_p_34.x = "10%";
ppt_p_34.y = "44%";
ppt_p_34.w ="80%";
ppt_p_34.isTextBox = true;
ppt_slide_29.addText(ppt_p_34_text, ppt_p_34);
ppt_slide_29_debug.items.push({ text: ppt_p_34_text, options: ppt_p_34 });
var ppt_p_35 = Object.assign({}, defaultStyle.content);
const ppt_p_35_text = "Con finanziamento adeguato (del Servizio Sanitario)";
ppt_p_35 = Object.assign({},ppt_p_35, (styles["para1"] || {}));
ppt_p_35.bullet = true;
ppt_p_35.color = "FF0000";
ppt_p_35.x = "10%";
ppt_p_35.y = "54%";
ppt_p_35.w ="80%";
ppt_p_35.isTextBox = true;
ppt_slide_29.addText(ppt_p_35_text, ppt_p_35);
ppt_slide_29_debug.items.push({ text: ppt_p_35_text, options: ppt_p_35 });
var ppt_p_36 = Object.assign({}, defaultStyle.content);
const ppt_p_36_text = "Garantiscono che ai genitori vengano fornite risorse credibili e affidabili.";
ppt_p_36 = Object.assign({},ppt_p_36, (styles["para1"] || {}));
ppt_p_36.x = "10%";
ppt_p_36.y = "64%";
ppt_p_36.w ="80%";
ppt_p_36.isTextBox = true;
ppt_slide_29.addText(ppt_p_36_text, ppt_p_36);
ppt_slide_29_debug.items.push({ text: ppt_p_36_text, options: ppt_p_36 });
var ppt_p_37 = Object.assign({}, defaultStyle.content);
const ppt_p_37_text = "Content and Quality of Infant Feeding Smartphone Apps: Five-Year Update on a Systematic Search and Evaluation";
ppt_p_37 = Object.assign({},ppt_p_37, (styles[".cite-article"] || {}));
ppt_p_37.x = "10%";
ppt_p_37.y = "76%";
ppt_p_37.w ="80%";
ppt_p_37.isTextBox = true;
ppt_slide_29.addText(ppt_p_37_text, ppt_p_37);
ppt_slide_29_debug.items.push({ text: ppt_p_37_text, options: ppt_p_37 });
var ppt_p_38 = Object.assign({}, defaultStyle.content);
const ppt_p_38_text = "Heilok Cheng, et all";
ppt_p_38 = Object.assign({},ppt_p_38, (styles[".cite-authors"] || {}));
ppt_p_38.x = "10%";
ppt_p_38.y = "80%";
ppt_p_38.w ="80%";
ppt_p_38.isTextBox = true;
ppt_slide_29.addText(ppt_p_38_text, ppt_p_38);
ppt_slide_29_debug.items.push({ text: ppt_p_38_text, options: ppt_p_38 });
var ppt_p_39 = Object.assign({}, defaultStyle.content);
const ppt_p_39_text = "A Mobile App, KhunLook, to Support Thai Parents and Caregivers With Child Health Supervision: Development, Validation, and Acceptability Study";
ppt_p_39 = Object.assign({},ppt_p_39, (styles[".cite-article"] || {}));
ppt_p_39.x = "10%";
ppt_p_39.y = "86%";
ppt_p_39.w ="80%";
ppt_p_39.isTextBox = true;
ppt_slide_29.addText(ppt_p_39_text, ppt_p_39);
ppt_slide_29_debug.items.push({ text: ppt_p_39_text, options: ppt_p_39 });
var ppt_p_40 = Object.assign({}, defaultStyle.content);
const ppt_p_40_text = "Rosawan Areemit";
ppt_p_40 = Object.assign({},ppt_p_40, (styles[".cite-authors"] || {}));
ppt_p_40.x = "10%";
ppt_p_40.y = "90%";
ppt_p_40.w ="80%";
ppt_p_40.isTextBox = true;
ppt_slide_29.addText(ppt_p_40_text, ppt_p_40);
ppt_slide_29_debug.items.push({ text: ppt_p_40_text, options: ppt_p_40 });
ppt_doc_1_debug.slides.push(ppt_slide_29_debug);
const ppt_slide_41 = ppt_doc_1.addSlide();
const ppt_slide_41_debug = { items: [] };
var ppt_p_42 = Object.assign({}, defaultStyle.content);
const ppt_p_42_text = "";
ppt_p_42 = Object.assign({},ppt_p_42, (styles["titolo1"] || {}));
ppt_p_42.isTextBox = true;
ppt_slide_41.addText(ppt_p_42_text, ppt_p_42);
ppt_slide_41_debug.items.push({ text: ppt_p_42_text, options: ppt_p_42 });
var ppt_p_43 = Object.assign({}, defaultStyle.content);
const ppt_p_43_text = "Una App aiuta i genitori?";
ppt_p_43 = Object.assign({},ppt_p_43, (styles["titolo2"] || {}));
ppt_p_43.isTextBox = true;
ppt_slide_41.addText(ppt_p_43_text, ppt_p_43);
ppt_slide_41_debug.items.push({ text: ppt_p_43_text, options: ppt_p_43 });
var ppt_p_44 = Object.assign({}, defaultStyle.content);
const ppt_p_44_text = "I genitori apprezzano le mHealth Apps.";
ppt_p_44 = Object.assign({},ppt_p_44, (styles["para1"] || {}));
ppt_p_44.x = "10%";
ppt_p_44.y = "24%";
ppt_p_44.w ="80%";
ppt_p_44.isTextBox = true;
ppt_slide_41.addText(ppt_p_44_text, ppt_p_44);
ppt_slide_41_debug.items.push({ text: ppt_p_44_text, options: ppt_p_44 });
var ppt_p_45 = Object.assign({}, defaultStyle.content);
const ppt_p_45_text = "Richiedono contatti brevi e ripetuti con informazioni pratiche.";
ppt_p_45 = Object.assign({},ppt_p_45, (styles["para1"] || {}));
ppt_p_45.x = "10%";
ppt_p_45.y = "34%";
ppt_p_45.w ="80%";
ppt_p_45.isTextBox = true;
ppt_slide_41.addText(ppt_p_45_text, ppt_p_45);
ppt_slide_41_debug.items.push({ text: ppt_p_45_text, options: ppt_p_45 });
var ppt_p_46 = Object.assign({}, defaultStyle.content);
const ppt_p_46_text = "Un programma eHealth di prevenzione dell'obesità infantile incentrato sui genitori può fornire supporto per migliorare l'alimentazione del bambino e l'autoefficacia parentale.";
ppt_p_46 = Object.assign({},ppt_p_46, (styles["para1"] || {}));
ppt_p_46.x = "10%";
ppt_p_46.y = "44%";
ppt_p_46.w ="80%";
ppt_p_46.isTextBox = true;
ppt_slide_41.addText(ppt_p_46_text, ppt_p_46);
ppt_slide_41_debug.items.push({ text: ppt_p_46_text, options: ppt_p_46 });
var ppt_p_47 = Object.assign({}, defaultStyle.content);
const ppt_p_47_text = "A Mobile App, KhunLook, to Support Thai Parents and Caregivers With Child Health Supervision: Development, Validation, and Acceptability Study";
ppt_p_47 = Object.assign({},ppt_p_47, (styles[".cite-article"] || {}));
ppt_p_47.x = "10%";
ppt_p_47.y = "56%";
ppt_p_47.w ="80%";
ppt_p_47.isTextBox = true;
ppt_slide_41.addText(ppt_p_47_text, ppt_p_47);
ppt_slide_41_debug.items.push({ text: ppt_p_47_text, options: ppt_p_47 });
var ppt_p_48 = Object.assign({}, defaultStyle.content);
const ppt_p_48_text = "Rosawan Areemit et all";
ppt_p_48 = Object.assign({},ppt_p_48, (styles[".cite-authors"] || {}));
ppt_p_48.x = "10%";
ppt_p_48.y = "60%";
ppt_p_48.w ="80%";
ppt_p_48.isTextBox = true;
ppt_slide_41.addText(ppt_p_48_text, ppt_p_48);
ppt_slide_41_debug.items.push({ text: ppt_p_48_text, options: ppt_p_48 });
var ppt_p_49 = Object.assign({}, defaultStyle.content);
const ppt_p_49_text = "An Internet-Based Childhood Obesity Prevention Program (Time2bHealthy) for Parents of Preschool-Aged Children.";
ppt_p_49 = Object.assign({},ppt_p_49, (styles[".cite-article"] || {}));
ppt_p_49.x = "10%";
ppt_p_49.y = "66%";
ppt_p_49.w ="80%";
ppt_p_49.isTextBox = true;
ppt_slide_41.addText(ppt_p_49_text, ppt_p_49);
ppt_slide_41_debug.items.push({ text: ppt_p_49_text, options: ppt_p_49 });
var ppt_p_50 = Object.assign({}, defaultStyle.content);
const ppt_p_50_text = "Megan L Hammersley et all";
ppt_p_50 = Object.assign({},ppt_p_50, (styles[".cite-authors"] || {}));
ppt_p_50.x = "10%";
ppt_p_50.y = "70%";
ppt_p_50.w ="80%";
ppt_p_50.isTextBox = true;
ppt_slide_41.addText(ppt_p_50_text, ppt_p_50);
ppt_slide_41_debug.items.push({ text: ppt_p_50_text, options: ppt_p_50 });
var ppt_p_51 = Object.assign({}, defaultStyle.content);
const ppt_p_51_text = "Randomized Controlled Trial J Med Internet Res, 2019 Feb 8;21(2):e11964. Doi: 10.2196/11964.";
ppt_p_51 = Object.assign({},ppt_p_51, (styles[".cite-review"] || {}));
ppt_p_51.x = "10%";
ppt_p_51.y = "74%";
ppt_p_51.w ="80%";
ppt_p_51.isTextBox = true;
ppt_slide_41.addText(ppt_p_51_text, ppt_p_51);
ppt_slide_41_debug.items.push({ text: ppt_p_51_text, options: ppt_p_51 });
var ppt_p_52 = Object.assign({}, defaultStyle.content);
const ppt_p_52_text = "A systematic evaluation of digital nutrition promotion websites and apps for supporting parents to influence children’s nutrition";
ppt_p_52 = Object.assign({},ppt_p_52, (styles[".cite-article"] || {}));
ppt_p_52.x = "10%";
ppt_p_52.y = "80%";
ppt_p_52.w ="80%";
ppt_p_52.isTextBox = true;
ppt_slide_41.addText(ppt_p_52_text, ppt_p_52);
ppt_slide_41_debug.items.push({ text: ppt_p_52_text, options: ppt_p_52 });
var ppt_p_53 = Object.assign({}, defaultStyle.content);
const ppt_p_53_text = "Dorota Zarnowiecki, et all";
ppt_p_53 = Object.assign({},ppt_p_53, (styles[".cite-authors"] || {}));
ppt_p_53.x = "10%";
ppt_p_53.y = "84%";
ppt_p_53.w ="80%";
ppt_p_53.isTextBox = true;
ppt_slide_41.addText(ppt_p_53_text, ppt_p_53);
ppt_slide_41_debug.items.push({ text: ppt_p_53_text, options: ppt_p_53 });
var ppt_p_54 = Object.assign({}, defaultStyle.content);
const ppt_p_54_text = "International Journal of Behavioral Nutrition and Physical Activity volume 17, Article number: 17 (2020)";
ppt_p_54 = Object.assign({},ppt_p_54, (styles[".cite-review"] || {}));
ppt_p_54.x = "10%";
ppt_p_54.y = "88%";
ppt_p_54.w ="80%";
ppt_p_54.isTextBox = true;
ppt_slide_41.addText(ppt_p_54_text, ppt_p_54);
ppt_slide_41_debug.items.push({ text: ppt_p_54_text, options: ppt_p_54 });
ppt_doc_1_debug.slides.push(ppt_slide_41_debug);
const ppt_slide_55 = ppt_doc_1.addSlide();
const ppt_slide_55_debug = { items: [] };
var ppt_p_56 = Object.assign({}, defaultStyle.content);
const ppt_p_56_text = "Tutti a tavola";
ppt_p_56 = Object.assign({},ppt_p_56, (styles["titolo1"] || {}));
ppt_p_56.isTextBox = true;
ppt_slide_55.addText(ppt_p_56_text, ppt_p_56);
ppt_slide_55_debug.items.push({ text: ppt_p_56_text, options: ppt_p_56 });
var ppt_p_57 = Object.assign({}, defaultStyle.content);
const ppt_p_57_text = "nascita";
ppt_p_57 = Object.assign({},ppt_p_57, (styles["titolo2"] || {}));
ppt_p_57.isTextBox = true;
ppt_slide_55.addText(ppt_p_57_text, ppt_p_57);
ppt_slide_55_debug.items.push({ text: ppt_p_57_text, options: ppt_p_57 });
const ppt_image_58 = {};
ppt_image_58.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_58.x = "20%";
ppt_image_58.y = "24%";
ppt_image_58.w ="29%";
ppt_image_58.h ="74%";
ppt_slide_55.addImage(ppt_image_58);
ppt_slide_55_debug.items.push({ image: ppt_image_58 });
const ppt_image_59 = {};
ppt_image_59.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/nascita.png";
ppt_image_59.x = "23%";
ppt_image_59.y = "31%";
ppt_image_59.w ="23%";
ppt_image_59.h ="63%";
ppt_slide_55.addImage(ppt_image_59);
ppt_slide_55_debug.items.push({ image: ppt_image_59 });
ppt_doc_1_debug.slides.push(ppt_slide_55_debug);
const ppt_slide_60 = ppt_doc_1.addSlide();
const ppt_slide_60_debug = { items: [] };
var ppt_p_61 = Object.assign({}, defaultStyle.content);
const ppt_p_61_text = "Tutti a tavola";
ppt_p_61 = Object.assign({},ppt_p_61, (styles["titolo1"] || {}));
ppt_p_61.isTextBox = true;
ppt_slide_60.addText(ppt_p_61_text, ppt_p_61);
ppt_slide_60_debug.items.push({ text: ppt_p_61_text, options: ppt_p_61 });
var ppt_p_62 = Object.assign({}, defaultStyle.content);
const ppt_p_62_text = "15 giorni";
ppt_p_62 = Object.assign({},ppt_p_62, (styles["titolo2"] || {}));
ppt_p_62.isTextBox = true;
ppt_slide_60.addText(ppt_p_62_text, ppt_p_62);
ppt_slide_60_debug.items.push({ text: ppt_p_62_text, options: ppt_p_62 });
const ppt_image_63 = {};
ppt_image_63.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_63.x = "20%";
ppt_image_63.y = "24%";
ppt_image_63.w ="29%";
ppt_image_63.h ="74%";
ppt_slide_60.addImage(ppt_image_63);
ppt_slide_60_debug.items.push({ image: ppt_image_63 });
const ppt_image_64 = {};
ppt_image_64.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/15 giorni.png";
ppt_image_64.x = "23%";
ppt_image_64.y = "31%";
ppt_image_64.w ="23%";
ppt_image_64.h ="63%";
ppt_slide_60.addImage(ppt_image_64);
ppt_slide_60_debug.items.push({ image: ppt_image_64 });
ppt_doc_1_debug.slides.push(ppt_slide_60_debug);
const ppt_slide_65 = ppt_doc_1.addSlide();
const ppt_slide_65_debug = { items: [] };
var ppt_p_66 = Object.assign({}, defaultStyle.content);
const ppt_p_66_text = "Tutti a tavola";
ppt_p_66 = Object.assign({},ppt_p_66, (styles["titolo1"] || {}));
ppt_p_66.isTextBox = true;
ppt_slide_65.addText(ppt_p_66_text, ppt_p_66);
ppt_slide_65_debug.items.push({ text: ppt_p_66_text, options: ppt_p_66 });
var ppt_p_67 = Object.assign({}, defaultStyle.content);
const ppt_p_67_text = "1 mese";
ppt_p_67 = Object.assign({},ppt_p_67, (styles["titolo2"] || {}));
ppt_p_67.isTextBox = true;
ppt_slide_65.addText(ppt_p_67_text, ppt_p_67);
ppt_slide_65_debug.items.push({ text: ppt_p_67_text, options: ppt_p_67 });
const ppt_image_68 = {};
ppt_image_68.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_68.x = "20%";
ppt_image_68.y = "24%";
ppt_image_68.w ="29%";
ppt_image_68.h ="74%";
ppt_slide_65.addImage(ppt_image_68);
ppt_slide_65_debug.items.push({ image: ppt_image_68 });
const ppt_image_69 = {};
ppt_image_69.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/1 mese.png";
ppt_image_69.x = "23%";
ppt_image_69.y = "31%";
ppt_image_69.w ="23%";
ppt_image_69.h ="63%";
ppt_slide_65.addImage(ppt_image_69);
ppt_slide_65_debug.items.push({ image: ppt_image_69 });
ppt_doc_1_debug.slides.push(ppt_slide_65_debug);
const ppt_slide_70 = ppt_doc_1.addSlide();
const ppt_slide_70_debug = { items: [] };
var ppt_p_71 = Object.assign({}, defaultStyle.content);
const ppt_p_71_text = "Tutti a tavola";
ppt_p_71 = Object.assign({},ppt_p_71, (styles["titolo1"] || {}));
ppt_p_71.isTextBox = true;
ppt_slide_70.addText(ppt_p_71_text, ppt_p_71);
ppt_slide_70_debug.items.push({ text: ppt_p_71_text, options: ppt_p_71 });
var ppt_p_72 = Object.assign({}, defaultStyle.content);
const ppt_p_72_text = "5 mesi";
ppt_p_72 = Object.assign({},ppt_p_72, (styles["titolo2"] || {}));
ppt_p_72.isTextBox = true;
ppt_slide_70.addText(ppt_p_72_text, ppt_p_72);
ppt_slide_70_debug.items.push({ text: ppt_p_72_text, options: ppt_p_72 });
const ppt_image_73 = {};
ppt_image_73.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_73.x = "20%";
ppt_image_73.y = "24%";
ppt_image_73.w ="29%";
ppt_image_73.h ="74%";
ppt_slide_70.addImage(ppt_image_73);
ppt_slide_70_debug.items.push({ image: ppt_image_73 });
const ppt_image_74 = {};
ppt_image_74.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/5 mesi.png";
ppt_image_74.x = "23%";
ppt_image_74.y = "31%";
ppt_image_74.w ="23%";
ppt_image_74.h ="63%";
ppt_slide_70.addImage(ppt_image_74);
ppt_slide_70_debug.items.push({ image: ppt_image_74 });
ppt_doc_1_debug.slides.push(ppt_slide_70_debug);
const ppt_slide_75 = ppt_doc_1.addSlide();
const ppt_slide_75_debug = { items: [] };
var ppt_p_76 = Object.assign({}, defaultStyle.content);
const ppt_p_76_text = "Tutti a tavola";
ppt_p_76 = Object.assign({},ppt_p_76, (styles["titolo1"] || {}));
ppt_p_76.isTextBox = true;
ppt_slide_75.addText(ppt_p_76_text, ppt_p_76);
ppt_slide_75_debug.items.push({ text: ppt_p_76_text, options: ppt_p_76 });
var ppt_p_77 = Object.assign({}, defaultStyle.content);
const ppt_p_77_text = "6 mesi";
ppt_p_77 = Object.assign({},ppt_p_77, (styles["titolo2"] || {}));
ppt_p_77.isTextBox = true;
ppt_slide_75.addText(ppt_p_77_text, ppt_p_77);
ppt_slide_75_debug.items.push({ text: ppt_p_77_text, options: ppt_p_77 });
const ppt_image_78 = {};
ppt_image_78.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_78.x = "20%";
ppt_image_78.y = "24%";
ppt_image_78.w ="29%";
ppt_image_78.h ="74%";
ppt_slide_75.addImage(ppt_image_78);
ppt_slide_75_debug.items.push({ image: ppt_image_78 });
const ppt_image_79 = {};
ppt_image_79.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/6 mesi.png";
ppt_image_79.x = "23%";
ppt_image_79.y = "31%";
ppt_image_79.w ="23%";
ppt_image_79.h ="63%";
ppt_slide_75.addImage(ppt_image_79);
ppt_slide_75_debug.items.push({ image: ppt_image_79 });
ppt_doc_1_debug.slides.push(ppt_slide_75_debug);
const ppt_slide_80 = ppt_doc_1.addSlide();
const ppt_slide_80_debug = { items: [] };
var ppt_p_81 = Object.assign({}, defaultStyle.content);
const ppt_p_81_text = "Tutti a tavola";
ppt_p_81 = Object.assign({},ppt_p_81, (styles["titolo1"] || {}));
ppt_p_81.isTextBox = true;
ppt_slide_80.addText(ppt_p_81_text, ppt_p_81);
ppt_slide_80_debug.items.push({ text: ppt_p_81_text, options: ppt_p_81 });
var ppt_p_82 = Object.assign({}, defaultStyle.content);
const ppt_p_82_text = "9 mesi/1";
ppt_p_82 = Object.assign({},ppt_p_82, (styles["titolo2"] || {}));
ppt_p_82.isTextBox = true;
ppt_slide_80.addText(ppt_p_82_text, ppt_p_82);
ppt_slide_80_debug.items.push({ text: ppt_p_82_text, options: ppt_p_82 });
const ppt_image_83 = {};
ppt_image_83.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_83.x = "20%";
ppt_image_83.y = "24%";
ppt_image_83.w ="29%";
ppt_image_83.h ="74%";
ppt_slide_80.addImage(ppt_image_83);
ppt_slide_80_debug.items.push({ image: ppt_image_83 });
const ppt_image_84 = {};
ppt_image_84.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/9 mesi 1.png";
ppt_image_84.x = "23%";
ppt_image_84.y = "31%";
ppt_image_84.w ="23%";
ppt_image_84.h ="63%";
ppt_slide_80.addImage(ppt_image_84);
ppt_slide_80_debug.items.push({ image: ppt_image_84 });
ppt_doc_1_debug.slides.push(ppt_slide_80_debug);
const ppt_slide_85 = ppt_doc_1.addSlide();
const ppt_slide_85_debug = { items: [] };
var ppt_p_86 = Object.assign({}, defaultStyle.content);
const ppt_p_86_text = "Tutti a tavola";
ppt_p_86 = Object.assign({},ppt_p_86, (styles["titolo1"] || {}));
ppt_p_86.isTextBox = true;
ppt_slide_85.addText(ppt_p_86_text, ppt_p_86);
ppt_slide_85_debug.items.push({ text: ppt_p_86_text, options: ppt_p_86 });
var ppt_p_87 = Object.assign({}, defaultStyle.content);
const ppt_p_87_text = "9 mesi/2";
ppt_p_87 = Object.assign({},ppt_p_87, (styles["titolo2"] || {}));
ppt_p_87.isTextBox = true;
ppt_slide_85.addText(ppt_p_87_text, ppt_p_87);
ppt_slide_85_debug.items.push({ text: ppt_p_87_text, options: ppt_p_87 });
const ppt_image_88 = {};
ppt_image_88.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_88.x = "20%";
ppt_image_88.y = "24%";
ppt_image_88.w ="29%";
ppt_image_88.h ="74%";
ppt_slide_85.addImage(ppt_image_88);
ppt_slide_85_debug.items.push({ image: ppt_image_88 });
const ppt_image_89 = {};
ppt_image_89.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/9 mesi 2.png";
ppt_image_89.x = "23%";
ppt_image_89.y = "31%";
ppt_image_89.w ="23%";
ppt_image_89.h ="63%";
ppt_slide_85.addImage(ppt_image_89);
ppt_slide_85_debug.items.push({ image: ppt_image_89 });
ppt_doc_1_debug.slides.push(ppt_slide_85_debug);
const ppt_slide_90 = ppt_doc_1.addSlide();
const ppt_slide_90_debug = { items: [] };
var ppt_p_91 = Object.assign({}, defaultStyle.content);
const ppt_p_91_text = "Tutti a tavola";
ppt_p_91 = Object.assign({},ppt_p_91, (styles["titolo1"] || {}));
ppt_p_91.isTextBox = true;
ppt_slide_90.addText(ppt_p_91_text, ppt_p_91);
ppt_slide_90_debug.items.push({ text: ppt_p_91_text, options: ppt_p_91 });
var ppt_p_92 = Object.assign({}, defaultStyle.content);
const ppt_p_92_text = "1 anno";
ppt_p_92 = Object.assign({},ppt_p_92, (styles["titolo2"] || {}));
ppt_p_92.isTextBox = true;
ppt_slide_90.addText(ppt_p_92_text, ppt_p_92);
ppt_slide_90_debug.items.push({ text: ppt_p_92_text, options: ppt_p_92 });
const ppt_image_93 = {};
ppt_image_93.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_93.x = "20%";
ppt_image_93.y = "24%";
ppt_image_93.w ="29%";
ppt_image_93.h ="74%";
ppt_slide_90.addImage(ppt_image_93);
ppt_slide_90_debug.items.push({ image: ppt_image_93 });
const ppt_image_94 = {};
ppt_image_94.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/1 anno.png";
ppt_image_94.x = "23%";
ppt_image_94.y = "31%";
ppt_image_94.w ="23%";
ppt_image_94.h ="63%";
ppt_slide_90.addImage(ppt_image_94);
ppt_slide_90_debug.items.push({ image: ppt_image_94 });
ppt_doc_1_debug.slides.push(ppt_slide_90_debug);
const ppt_slide_95 = ppt_doc_1.addSlide();
const ppt_slide_95_debug = { items: [] };
var ppt_p_96 = Object.assign({}, defaultStyle.content);
const ppt_p_96_text = "Tutti a tavola";
ppt_p_96 = Object.assign({},ppt_p_96, (styles["titolo1"] || {}));
ppt_p_96.isTextBox = true;
ppt_slide_95.addText(ppt_p_96_text, ppt_p_96);
ppt_slide_95_debug.items.push({ text: ppt_p_96_text, options: ppt_p_96 });
var ppt_p_97 = Object.assign({}, defaultStyle.content);
const ppt_p_97_text = "14 mesi";
ppt_p_97 = Object.assign({},ppt_p_97, (styles["titolo2"] || {}));
ppt_p_97.isTextBox = true;
ppt_slide_95.addText(ppt_p_97_text, ppt_p_97);
ppt_slide_95_debug.items.push({ text: ppt_p_97_text, options: ppt_p_97 });
const ppt_image_98 = {};
ppt_image_98.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_98.x = "20%";
ppt_image_98.y = "24%";
ppt_image_98.w ="29%";
ppt_image_98.h ="74%";
ppt_slide_95.addImage(ppt_image_98);
ppt_slide_95_debug.items.push({ image: ppt_image_98 });
const ppt_image_99 = {};
ppt_image_99.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/14 mesi.png";
ppt_image_99.x = "23%";
ppt_image_99.y = "31%";
ppt_image_99.w ="23%";
ppt_image_99.h ="63%";
ppt_slide_95.addImage(ppt_image_99);
ppt_slide_95_debug.items.push({ image: ppt_image_99 });
ppt_doc_1_debug.slides.push(ppt_slide_95_debug);
const ppt_slide_100 = ppt_doc_1.addSlide();
const ppt_slide_100_debug = { items: [] };
var ppt_p_101 = Object.assign({}, defaultStyle.content);
const ppt_p_101_text = "Tutti a tavola";
ppt_p_101 = Object.assign({},ppt_p_101, (styles["titolo1"] || {}));
ppt_p_101.isTextBox = true;
ppt_slide_100.addText(ppt_p_101_text, ppt_p_101);
ppt_slide_100_debug.items.push({ text: ppt_p_101_text, options: ppt_p_101 });
var ppt_p_102 = Object.assign({}, defaultStyle.content);
const ppt_p_102_text = "17 mesi 1";
ppt_p_102 = Object.assign({},ppt_p_102, (styles["titolo2"] || {}));
ppt_p_102.isTextBox = true;
ppt_slide_100.addText(ppt_p_102_text, ppt_p_102);
ppt_slide_100_debug.items.push({ text: ppt_p_102_text, options: ppt_p_102 });
const ppt_image_103 = {};
ppt_image_103.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_103.x = "20%";
ppt_image_103.y = "24%";
ppt_image_103.w ="29%";
ppt_image_103.h ="74%";
ppt_slide_100.addImage(ppt_image_103);
ppt_slide_100_debug.items.push({ image: ppt_image_103 });
const ppt_image_104 = {};
ppt_image_104.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/17 m 1.png";
ppt_image_104.x = "23%";
ppt_image_104.y = "31%";
ppt_image_104.w ="23%";
ppt_image_104.h ="63%";
ppt_slide_100.addImage(ppt_image_104);
ppt_slide_100_debug.items.push({ image: ppt_image_104 });
ppt_doc_1_debug.slides.push(ppt_slide_100_debug);
const ppt_slide_105 = ppt_doc_1.addSlide();
const ppt_slide_105_debug = { items: [] };
var ppt_p_106 = Object.assign({}, defaultStyle.content);
const ppt_p_106_text = "Tutti a tavola";
ppt_p_106 = Object.assign({},ppt_p_106, (styles["titolo1"] || {}));
ppt_p_106.isTextBox = true;
ppt_slide_105.addText(ppt_p_106_text, ppt_p_106);
ppt_slide_105_debug.items.push({ text: ppt_p_106_text, options: ppt_p_106 });
var ppt_p_107 = Object.assign({}, defaultStyle.content);
const ppt_p_107_text = "17 mesi 2";
ppt_p_107 = Object.assign({},ppt_p_107, (styles["titolo2"] || {}));
ppt_p_107.isTextBox = true;
ppt_slide_105.addText(ppt_p_107_text, ppt_p_107);
ppt_slide_105_debug.items.push({ text: ppt_p_107_text, options: ppt_p_107 });
const ppt_image_108 = {};
ppt_image_108.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_108.x = "20%";
ppt_image_108.y = "24%";
ppt_image_108.w ="29%";
ppt_image_108.h ="74%";
ppt_slide_105.addImage(ppt_image_108);
ppt_slide_105_debug.items.push({ image: ppt_image_108 });
const ppt_image_109 = {};
ppt_image_109.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/17 m 2.png";
ppt_image_109.x = "23%";
ppt_image_109.y = "31%";
ppt_image_109.w ="23%";
ppt_image_109.h ="63%";
ppt_slide_105.addImage(ppt_image_109);
ppt_slide_105_debug.items.push({ image: ppt_image_109 });
ppt_doc_1_debug.slides.push(ppt_slide_105_debug);
const ppt_slide_110 = ppt_doc_1.addSlide();
const ppt_slide_110_debug = { items: [] };
var ppt_p_111 = Object.assign({}, defaultStyle.content);
const ppt_p_111_text = "Tutti a tavola";
ppt_p_111 = Object.assign({},ppt_p_111, (styles["titolo1"] || {}));
ppt_p_111.isTextBox = true;
ppt_slide_110.addText(ppt_p_111_text, ppt_p_111);
ppt_slide_110_debug.items.push({ text: ppt_p_111_text, options: ppt_p_111 });
var ppt_p_112 = Object.assign({}, defaultStyle.content);
const ppt_p_112_text = "18 mesi";
ppt_p_112 = Object.assign({},ppt_p_112, (styles["titolo2"] || {}));
ppt_p_112.isTextBox = true;
ppt_slide_110.addText(ppt_p_112_text, ppt_p_112);
ppt_slide_110_debug.items.push({ text: ppt_p_112_text, options: ppt_p_112 });
const ppt_image_113 = {};
ppt_image_113.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_113.x = "20%";
ppt_image_113.y = "24%";
ppt_image_113.w ="29%";
ppt_image_113.h ="74%";
ppt_slide_110.addImage(ppt_image_113);
ppt_slide_110_debug.items.push({ image: ppt_image_113 });
const ppt_image_114 = {};
ppt_image_114.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/18 mesi.png";
ppt_image_114.x = "23%";
ppt_image_114.y = "31%";
ppt_image_114.w ="23%";
ppt_image_114.h ="63%";
ppt_slide_110.addImage(ppt_image_114);
ppt_slide_110_debug.items.push({ image: ppt_image_114 });
ppt_doc_1_debug.slides.push(ppt_slide_110_debug);
const ppt_slide_115 = ppt_doc_1.addSlide();
const ppt_slide_115_debug = { items: [] };
var ppt_p_116 = Object.assign({}, defaultStyle.content);
const ppt_p_116_text = "Tutti a tavola";
ppt_p_116 = Object.assign({},ppt_p_116, (styles["titolo1"] || {}));
ppt_p_116.isTextBox = true;
ppt_slide_115.addText(ppt_p_116_text, ppt_p_116);
ppt_slide_115_debug.items.push({ text: ppt_p_116_text, options: ppt_p_116 });
var ppt_p_117 = Object.assign({}, defaultStyle.content);
const ppt_p_117_text = "19 mesi";
ppt_p_117 = Object.assign({},ppt_p_117, (styles["titolo2"] || {}));
ppt_p_117.isTextBox = true;
ppt_slide_115.addText(ppt_p_117_text, ppt_p_117);
ppt_slide_115_debug.items.push({ text: ppt_p_117_text, options: ppt_p_117 });
const ppt_image_118 = {};
ppt_image_118.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_118.x = "20%";
ppt_image_118.y = "24%";
ppt_image_118.w ="29%";
ppt_image_118.h ="74%";
ppt_slide_115.addImage(ppt_image_118);
ppt_slide_115_debug.items.push({ image: ppt_image_118 });
const ppt_image_119 = {};
ppt_image_119.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/19 mesi.png";
ppt_image_119.x = "23%";
ppt_image_119.y = "31%";
ppt_image_119.w ="23%";
ppt_image_119.h ="63%";
ppt_slide_115.addImage(ppt_image_119);
ppt_slide_115_debug.items.push({ image: ppt_image_119 });
ppt_doc_1_debug.slides.push(ppt_slide_115_debug);
const ppt_slide_120 = ppt_doc_1.addSlide();
const ppt_slide_120_debug = { items: [] };
var ppt_p_121 = Object.assign({}, defaultStyle.content);
const ppt_p_121_text = "Tutti a tavola";
ppt_p_121 = Object.assign({},ppt_p_121, (styles["titolo1"] || {}));
ppt_p_121.isTextBox = true;
ppt_slide_120.addText(ppt_p_121_text, ppt_p_121);
ppt_slide_120_debug.items.push({ text: ppt_p_121_text, options: ppt_p_121 });
var ppt_p_122 = Object.assign({}, defaultStyle.content);
const ppt_p_122_text = " ";
ppt_p_122 = Object.assign({},ppt_p_122, (styles["titolo2"] || {}));
ppt_p_122.isTextBox = true;
ppt_slide_120.addText(ppt_p_122_text, ppt_p_122);
ppt_slide_120_debug.items.push({ text: ppt_p_122_text, options: ppt_p_122 });
var ppt_p_123 = Object.assign({}, defaultStyle.content);
const ppt_p_123_text = "20 mesi";
ppt_p_123 = Object.assign({},ppt_p_123, (styles[".column-title"] || {}));
ppt_p_123.x = "10%";
ppt_p_123.y = "24%";
ppt_p_123.w ="40%";
ppt_p_123.breakLine = true;
ppt_p_123.isTextBox = true;
ppt_slide_120.addText(ppt_p_123_text, ppt_p_123);
ppt_slide_120_debug.items.push({ text: ppt_p_123_text, options: ppt_p_123 });
var ppt_p_124 = Object.assign({}, defaultStyle.content);
const ppt_p_124_text = "Gli inquinanti alimentari";
ppt_p_124 = Object.assign({},ppt_p_124, (styles[".column-p"] || {}));
ppt_p_124.x = "10%";
ppt_p_124.y = "30%";
ppt_p_124.w ="40%";
ppt_p_124.breakLine = true;
ppt_p_124.isTextBox = true;
ppt_slide_120.addText(ppt_p_124_text, ppt_p_124);
ppt_slide_120_debug.items.push({ text: ppt_p_124_text, options: ppt_p_124 });
var ppt_p_125 = Object.assign({}, defaultStyle.content);
const ppt_p_125_text = "21 mesi";
ppt_p_125 = Object.assign({},ppt_p_125, (styles[".column-title"] || {}));
ppt_p_125.x = "10%";
ppt_p_125.y = "38%";
ppt_p_125.w ="40%";
ppt_p_125.breakLine = true;
ppt_p_125.isTextBox = true;
ppt_slide_120.addText(ppt_p_125_text, ppt_p_125);
ppt_slide_120_debug.items.push({ text: ppt_p_125_text, options: ppt_p_125 });
var ppt_p_126 = Object.assign({}, defaultStyle.content);
const ppt_p_126_text = "I pericoli in cucina";
ppt_p_126 = Object.assign({},ppt_p_126, (styles[".column-p"] || {}));
ppt_p_126.x = "10%";
ppt_p_126.y = "44%";
ppt_p_126.w ="40%";
ppt_p_126.breakLine = true;
ppt_p_126.isTextBox = true;
ppt_slide_120.addText(ppt_p_126_text, ppt_p_126);
ppt_slide_120_debug.items.push({ text: ppt_p_126_text, options: ppt_p_126 });
var ppt_p_127 = Object.assign({}, defaultStyle.content);
const ppt_p_127_text = "22 mesi";
ppt_p_127 = Object.assign({},ppt_p_127, (styles[".column-title"] || {}));
ppt_p_127.x = "10%";
ppt_p_127.y = "52%";
ppt_p_127.w ="40%";
ppt_p_127.breakLine = true;
ppt_p_127.isTextBox = true;
ppt_slide_120.addText(ppt_p_127_text, ppt_p_127);
ppt_slide_120_debug.items.push({ text: ppt_p_127_text, options: ppt_p_127 });
var ppt_p_128 = Object.assign({}, defaultStyle.content);
const ppt_p_128_text = "Il bisogno di fibre";
ppt_p_128 = Object.assign({},ppt_p_128, (styles[".column-p"] || {}));
ppt_p_128.x = "10%";
ppt_p_128.y = "58%";
ppt_p_128.w ="40%";
ppt_p_128.breakLine = true;
ppt_p_128.isTextBox = true;
ppt_slide_120.addText(ppt_p_128_text, ppt_p_128);
ppt_slide_120_debug.items.push({ text: ppt_p_128_text, options: ppt_p_128 });
var ppt_p_129 = Object.assign({}, defaultStyle.content);
const ppt_p_129_text = "2 anni";
ppt_p_129 = Object.assign({},ppt_p_129, (styles[".column-title"] || {}));
ppt_p_129.x = "10%";
ppt_p_129.y = "66%";
ppt_p_129.w ="40%";
ppt_p_129.breakLine = true;
ppt_p_129.isTextBox = true;
ppt_slide_120.addText(ppt_p_129_text, ppt_p_129);
ppt_slide_120_debug.items.push({ text: ppt_p_129_text, options: ppt_p_129 });
var ppt_p_130 = Object.assign({}, defaultStyle.content);
const ppt_p_130_text = "Buone abitudini e strategie per invogliare il tuo bambino a mangiare cibi salutari";
ppt_p_130 = Object.assign({},ppt_p_130, (styles[".column-p"] || {}));
ppt_p_130.x = "10%";
ppt_p_130.y = "72%";
ppt_p_130.w ="40%";
ppt_p_130.breakLine = true;
ppt_p_130.isTextBox = true;
ppt_slide_120.addText(ppt_p_130_text, ppt_p_130);
ppt_slide_120_debug.items.push({ text: ppt_p_130_text, options: ppt_p_130 });
var ppt_p_131 = Object.assign({}, defaultStyle.content);
const ppt_p_131_text = "3 anni e 2 mesi";
ppt_p_131 = Object.assign({},ppt_p_131, (styles[".column-title"] || {}));
ppt_p_131.x = "10%";
ppt_p_131.y = "80%";
ppt_p_131.w ="40%";
ppt_p_131.breakLine = true;
ppt_p_131.isTextBox = true;
ppt_slide_120.addText(ppt_p_131_text, ppt_p_131);
ppt_slide_120_debug.items.push({ text: ppt_p_131_text, options: ppt_p_131 });
var ppt_p_132 = Object.assign({}, defaultStyle.content);
const ppt_p_132_text = "E se non vuole mangiare frutta e verdura?";
ppt_p_132 = Object.assign({},ppt_p_132, (styles[".column-p"] || {}));
ppt_p_132.x = "10%";
ppt_p_132.y = "86%";
ppt_p_132.w ="40%";
ppt_p_132.breakLine = true;
ppt_p_132.isTextBox = true;
ppt_slide_120.addText(ppt_p_132_text, ppt_p_132);
ppt_slide_120_debug.items.push({ text: ppt_p_132_text, options: ppt_p_132 });
const ppt_image_133 = {};
ppt_image_133.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/l'orto dei piccoli.jpg";
ppt_image_133.y = "24%";
ppt_image_133.x = "55%";
ppt_image_133.w ="22%";
ppt_image_133.h ="25%";
ppt_slide_120.addImage(ppt_image_133);
ppt_slide_120_debug.items.push({ image: ppt_image_133 });
const ppt_image_134 = {};
ppt_image_134.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/mangia i piselli.jpg";
ppt_image_134.y = "54%";
ppt_image_134.x = "55%";
ppt_image_134.w ="22%";
ppt_image_134.h ="25%";
ppt_slide_120.addImage(ppt_image_134);
ppt_slide_120_debug.items.push({ image: ppt_image_134 });
ppt_doc_1_debug.slides.push(ppt_slide_120_debug);
const ppt_slide_135 = ppt_doc_1.addSlide();
const ppt_slide_135_debug = { items: [] };
var ppt_p_136 = Object.assign({}, defaultStyle.content);
const ppt_p_136_text = "Tutti a tavola";
ppt_p_136 = Object.assign({},ppt_p_136, (styles["titolo1"] || {}));
ppt_p_136.isTextBox = true;
ppt_slide_135.addText(ppt_p_136_text, ppt_p_136);
ppt_slide_135_debug.items.push({ text: ppt_p_136_text, options: ppt_p_136 });
var ppt_p_137 = Object.assign({}, defaultStyle.content);
const ppt_p_137_text = " ";
ppt_p_137 = Object.assign({},ppt_p_137, (styles["titolo2"] || {}));
ppt_p_137.isTextBox = true;
ppt_slide_135.addText(ppt_p_137_text, ppt_p_137);
ppt_slide_135_debug.items.push({ text: ppt_p_137_text, options: ppt_p_137 });
var ppt_p_138 = Object.assign({}, defaultStyle.content);
const ppt_p_138_text = "3 anni e 6 mesi";
ppt_p_138 = Object.assign({},ppt_p_138, (styles[".column-title"] || {}));
ppt_p_138.x = "10%";
ppt_p_138.y = "24%";
ppt_p_138.w ="40%";
ppt_p_138.breakLine = true;
ppt_p_138.isTextBox = true;
ppt_slide_135.addText(ppt_p_138_text, ppt_p_138);
ppt_slide_135_debug.items.push({ text: ppt_p_138_text, options: ppt_p_138 });
var ppt_p_139 = Object.assign({}, defaultStyle.content);
const ppt_p_139_text = "Cerca di rendere più sani i tuoi piatti preferiti. Leggere un libro aiuta a mangiare cibi sani.";
ppt_p_139 = Object.assign({},ppt_p_139, (styles[".column-p"] || {}));
ppt_p_139.x = "10%";
ppt_p_139.y = "30%";
ppt_p_139.w ="40%";
ppt_p_139.breakLine = true;
ppt_p_139.isTextBox = true;
ppt_slide_135.addText(ppt_p_139_text, ppt_p_139);
ppt_slide_135_debug.items.push({ text: ppt_p_139_text, options: ppt_p_139 });
var ppt_p_140 = Object.assign({}, defaultStyle.content);
const ppt_p_140_text = "4 anni e 6 mesi";
ppt_p_140 = Object.assign({},ppt_p_140, (styles[".column-title"] || {}));
ppt_p_140.x = "10%";
ppt_p_140.y = "38%";
ppt_p_140.w ="40%";
ppt_p_140.breakLine = true;
ppt_p_140.isTextBox = true;
ppt_slide_135.addText(ppt_p_140_text, ppt_p_140);
ppt_slide_135_debug.items.push({ text: ppt_p_140_text, options: ppt_p_140 });
var ppt_p_141 = Object.assign({}, defaultStyle.content);
const ppt_p_141_text = "Come fare per essere un modello sano?";
ppt_p_141 = Object.assign({},ppt_p_141, (styles[".column-p"] || {}));
ppt_p_141.x = "10%";
ppt_p_141.y = "44%";
ppt_p_141.w ="40%";
ppt_p_141.breakLine = true;
ppt_p_141.isTextBox = true;
ppt_slide_135.addText(ppt_p_141_text, ppt_p_141);
ppt_slide_135_debug.items.push({ text: ppt_p_141_text, options: ppt_p_141 });
var ppt_p_142 = Object.assign({}, defaultStyle.content);
const ppt_p_142_text = "5 anni e 3 mesi";
ppt_p_142 = Object.assign({},ppt_p_142, (styles[".column-title"] || {}));
ppt_p_142.x = "10%";
ppt_p_142.y = "52%";
ppt_p_142.w ="40%";
ppt_p_142.breakLine = true;
ppt_p_142.isTextBox = true;
ppt_slide_135.addText(ppt_p_142_text, ppt_p_142);
ppt_slide_135_debug.items.push({ text: ppt_p_142_text, options: ppt_p_142 });
var ppt_p_143 = Object.assign({}, defaultStyle.content);
const ppt_p_143_text = "Fra i 5 e i 6 anni sarà molto utile un Bilancio di salute dal tuo pediatra";
ppt_p_143 = Object.assign({},ppt_p_143, (styles[".column-p"] || {}));
ppt_p_143.x = "10%";
ppt_p_143.y = "58%";
ppt_p_143.w ="40%";
ppt_p_143.breakLine = true;
ppt_p_143.isTextBox = true;
ppt_slide_135.addText(ppt_p_143_text, ppt_p_143);
ppt_slide_135_debug.items.push({ text: ppt_p_143_text, options: ppt_p_143 });
const ppt_image_144 = {};
ppt_image_144.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/musi piatti.jpg";
ppt_image_144.y = "20%";
ppt_image_144.x = "55%";
ppt_image_144.w ="20%";
ppt_image_144.h ="20%";
ppt_slide_135.addImage(ppt_image_144);
ppt_slide_135_debug.items.push({ image: ppt_image_144 });
const ppt_image_145 = {};
ppt_image_145.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/è ora di mangiare sano.jpg";
ppt_image_145.y = "45%";
ppt_image_145.x = "55%";
ppt_image_145.w ="20%";
ppt_image_145.h ="20%";
ppt_slide_135.addImage(ppt_image_145);
ppt_slide_135_debug.items.push({ image: ppt_image_145 });
const ppt_image_146 = {};
ppt_image_146.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/bminforma.png";
ppt_image_146.y = "70%";
ppt_image_146.x = "55%";
ppt_image_146.w ="20%";
ppt_image_146.h ="20%";
ppt_slide_135.addImage(ppt_image_146);
ppt_slide_135_debug.items.push({ image: ppt_image_146 });
ppt_doc_1_debug.slides.push(ppt_slide_135_debug);
const ppt_slide_147 = ppt_doc_1.addSlide();
const ppt_slide_147_debug = { items: [] };
var ppt_p_148 = Object.assign({}, defaultStyle.content);
const ppt_p_148_text = "Tutti a tavola";
ppt_p_148 = Object.assign({},ppt_p_148, (styles["titolo1"] || {}));
ppt_p_148.isTextBox = true;
ppt_slide_147.addText(ppt_p_148_text, ppt_p_148);
ppt_slide_147_debug.items.push({ text: ppt_p_148_text, options: ppt_p_148 });
var ppt_p_149 = Object.assign({}, defaultStyle.content);
const ppt_p_149_text = "5 anni e 9 mesi/1";
ppt_p_149 = Object.assign({},ppt_p_149, (styles["titolo2"] || {}));
ppt_p_149.isTextBox = true;
ppt_slide_147.addText(ppt_p_149_text, ppt_p_149);
ppt_slide_147_debug.items.push({ text: ppt_p_149_text, options: ppt_p_149 });
const ppt_image_150 = {};
ppt_image_150.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_150.x = "20%";
ppt_image_150.y = "24%";
ppt_image_150.w ="29%";
ppt_image_150.h ="74%";
ppt_slide_147.addImage(ppt_image_150);
ppt_slide_147_debug.items.push({ image: ppt_image_150 });
const ppt_image_151 = {};
ppt_image_151.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/5a 9 m.png";
ppt_image_151.x = "23%";
ppt_image_151.y = "31%";
ppt_image_151.w ="23%";
ppt_image_151.h ="63%";
ppt_slide_147.addImage(ppt_image_151);
ppt_slide_147_debug.items.push({ image: ppt_image_151 });
ppt_doc_1_debug.slides.push(ppt_slide_147_debug);
const ppt_slide_152 = ppt_doc_1.addSlide();
const ppt_slide_152_debug = { items: [] };
var ppt_p_153 = Object.assign({}, defaultStyle.content);
const ppt_p_153_text = "Tutti a tavola";
ppt_p_153 = Object.assign({},ppt_p_153, (styles["titolo1"] || {}));
ppt_p_153.isTextBox = true;
ppt_slide_152.addText(ppt_p_153_text, ppt_p_153);
ppt_slide_152_debug.items.push({ text: ppt_p_153_text, options: ppt_p_153 });
var ppt_p_154 = Object.assign({}, defaultStyle.content);
const ppt_p_154_text = "5 anni e 9 mesi/2";
ppt_p_154 = Object.assign({},ppt_p_154, (styles["titolo2"] || {}));
ppt_p_154.isTextBox = true;
ppt_slide_152.addText(ppt_p_154_text, ppt_p_154);
ppt_slide_152_debug.items.push({ text: ppt_p_154_text, options: ppt_p_154 });
const ppt_image_155 = {};
ppt_image_155.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_155.x = "20%";
ppt_image_155.y = "24%";
ppt_image_155.w ="29%";
ppt_image_155.h ="74%";
ppt_slide_152.addImage(ppt_image_155);
ppt_slide_152_debug.items.push({ image: ppt_image_155 });
const ppt_image_156 = {};
ppt_image_156.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/5a 9m 2.png";
ppt_image_156.x = "23%";
ppt_image_156.y = "31%";
ppt_image_156.w ="23%";
ppt_image_156.h ="63%";
ppt_slide_152.addImage(ppt_image_156);
ppt_slide_152_debug.items.push({ image: ppt_image_156 });
ppt_doc_1_debug.slides.push(ppt_slide_152_debug);
const ppt_slide_157 = ppt_doc_1.addSlide();
const ppt_slide_157_debug = { items: [] };
var ppt_p_158 = Object.assign({}, defaultStyle.content);
const ppt_p_158_text = "Tutti a tavola";
ppt_p_158 = Object.assign({},ppt_p_158, (styles["titolo1"] || {}));
ppt_p_158.isTextBox = true;
ppt_slide_157.addText(ppt_p_158_text, ppt_p_158);
ppt_slide_157_debug.items.push({ text: ppt_p_158_text, options: ppt_p_158 });
var ppt_p_159 = Object.assign({}, defaultStyle.content);
const ppt_p_159_text = "6 anni";
ppt_p_159 = Object.assign({},ppt_p_159, (styles["titolo2"] || {}));
ppt_p_159.isTextBox = true;
ppt_slide_157.addText(ppt_p_159_text, ppt_p_159);
ppt_slide_157_debug.items.push({ text: ppt_p_159_text, options: ppt_p_159 });
var ppt_p_160 = Object.assign({}, defaultStyle.content);
const ppt_p_160_text = "";
ppt_p_160 = Object.assign({},ppt_p_160, (styles[".column-title"] || {}));
ppt_p_160.x = "10%";
ppt_p_160.y = "24%";
ppt_p_160.w ="40%";
ppt_p_160.breakLine = true;
ppt_p_160.isTextBox = true;
ppt_slide_157.addText(ppt_p_160_text, ppt_p_160);
ppt_slide_157_debug.items.push({ text: ppt_p_160_text, options: ppt_p_160 });
var ppt_p_161 = Object.assign({}, defaultStyle.content);
const ppt_p_161_text = "Coltiva un piccolo orto domestico";
ppt_p_161 = Object.assign({},ppt_p_161, (styles[".column-p"] || {}));
ppt_p_161.x = "10%";
ppt_p_161.y = "30%";
ppt_p_161.w ="40%";
ppt_p_161.breakLine = true;
ppt_p_161.isTextBox = true;
ppt_slide_157.addText(ppt_p_161_text, ppt_p_161);
ppt_slide_157_debug.items.push({ text: ppt_p_161_text, options: ppt_p_161 });
const ppt_image_162 = {};
ppt_image_162.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/l'orto dei bimbi.jpg";
ppt_image_162.y = "24%";
ppt_image_162.x = "55%";
ppt_image_162.w ="22%";
ppt_image_162.h ="25%";
ppt_slide_157.addImage(ppt_image_162);
ppt_slide_157_debug.items.push({ image: ppt_image_162 });
const ppt_image_163 = {};
ppt_image_163.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/bimbi orticoltori.jpg";
ppt_image_163.y = "54%";
ppt_image_163.x = "55%";
ppt_image_163.w ="22%";
ppt_image_163.h ="25%";
ppt_slide_157.addImage(ppt_image_163);
ppt_slide_157_debug.items.push({ image: ppt_image_163 });
ppt_doc_1_debug.slides.push(ppt_slide_157_debug);
const ppt_slide_164 = ppt_doc_1.addSlide();
const ppt_slide_164_debug = { items: [] };
var ppt_p_165 = Object.assign({}, defaultStyle.content);
const ppt_p_165_text = "Tutti a tavola";
ppt_p_165 = Object.assign({},ppt_p_165, (styles["titolo1"] || {}));
ppt_p_165.isTextBox = true;
ppt_slide_164.addText(ppt_p_165_text, ppt_p_165);
ppt_slide_164_debug.items.push({ text: ppt_p_165_text, options: ppt_p_165 });
var ppt_p_166 = Object.assign({}, defaultStyle.content);
const ppt_p_166_text = " ";
ppt_p_166 = Object.assign({},ppt_p_166, (styles["titolo2"] || {}));
ppt_p_166.isTextBox = true;
ppt_slide_164.addText(ppt_p_166_text, ppt_p_166);
ppt_slide_164_debug.items.push({ text: ppt_p_166_text, options: ppt_p_166 });
var ppt_p_167 = Object.assign({}, defaultStyle.content);
const ppt_p_167_text = "6 anni";
ppt_p_167 = Object.assign({},ppt_p_167, (styles[".column-title"] || {}));
ppt_p_167.x = "10%";
ppt_p_167.y = "24%";
ppt_p_167.w ="40%";
ppt_p_167.breakLine = true;
ppt_p_167.isTextBox = true;
ppt_slide_164.addText(ppt_p_167_text, ppt_p_167);
ppt_slide_164_debug.items.push({ text: ppt_p_167_text, options: ppt_p_167 });
var ppt_p_168 = Object.assign({}, defaultStyle.content);
const ppt_p_168_text = "Diventa un critico gastronomico... I momenti speciali a tavola uniscono la famiglia";
ppt_p_168 = Object.assign({},ppt_p_168, (styles[".column-p"] || {}));
ppt_p_168.x = "10%";
ppt_p_168.y = "30%";
ppt_p_168.w ="40%";
ppt_p_168.breakLine = true;
ppt_p_168.isTextBox = true;
ppt_slide_164.addText(ppt_p_168_text, ppt_p_168);
ppt_slide_164_debug.items.push({ text: ppt_p_168_text, options: ppt_p_168 });
const ppt_image_169 = {};
ppt_image_169.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/3 cuochi.jpg";
ppt_image_169.y = "24%";
ppt_image_169.x = "55%";
ppt_image_169.w ="22%";
ppt_image_169.h ="25%";
ppt_slide_164.addImage(ppt_image_169);
ppt_slide_164_debug.items.push({ image: ppt_image_169 });
const ppt_image_170 = {};
ppt_image_170.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/momenti speciali a tavola.jpg";
ppt_image_170.y = "54%";
ppt_image_170.x = "55%";
ppt_image_170.w ="22%";
ppt_image_170.h ="25%";
ppt_slide_164.addImage(ppt_image_170);
ppt_slide_164_debug.items.push({ image: ppt_image_170 });
ppt_doc_1_debug.slides.push(ppt_slide_164_debug);
const ppt_slide_171 = ppt_doc_1.addSlide();
const ppt_slide_171_debug = { items: [] };
var ppt_p_172 = Object.assign({}, defaultStyle.content);
const ppt_p_172_text = "NpL e NpM";
ppt_p_172 = Object.assign({},ppt_p_172, (styles["titolo1"] || {}));
ppt_p_172.isTextBox = true;
ppt_slide_171.addText(ppt_p_172_text, ppt_p_172);
ppt_slide_171_debug.items.push({ text: ppt_p_172_text, options: ppt_p_172 });
var ppt_p_173 = Object.assign({}, defaultStyle.content);
const ppt_p_173_text = " ";
ppt_p_173 = Object.assign({},ppt_p_173, (styles["titolo2"] || {}));
ppt_p_173.isTextBox = true;
ppt_slide_171.addText(ppt_p_173_text, ppt_p_173);
ppt_slide_171_debug.items.push({ text: ppt_p_173_text, options: ppt_p_173 });
var ppt_p_174 = Object.assign({}, defaultStyle.content);
const ppt_p_174_text = "Proposte di libri e ascolti musicali per le varie età";
ppt_p_174 = Object.assign({},ppt_p_174, (styles["para1"] || {}));
ppt_p_174.x = "10%";
ppt_p_174.y = "24%";
ppt_p_174.w ="80%";
ppt_p_174.isTextBox = true;
ppt_slide_171.addText(ppt_p_174_text, ppt_p_174);
ppt_slide_171_debug.items.push({ text: ppt_p_174_text, options: ppt_p_174 });
var ppt_p_175 = Object.assign({}, defaultStyle.content);
const ppt_p_175_text = "Consigli";
ppt_p_175 = Object.assign({},ppt_p_175, (styles["para1"] || {}));
ppt_p_175.x = "10%";
ppt_p_175.y = "34%";
ppt_p_175.w ="80%";
ppt_p_175.isTextBox = true;
ppt_slide_171.addText(ppt_p_175_text, ppt_p_175);
ppt_slide_171_debug.items.push({ text: ppt_p_175_text, options: ppt_p_175 });
var ppt_p_176 = Object.assign({}, defaultStyle.content);
const ppt_p_176_text = "Tanti libri di qualità per ogni età";
ppt_p_176 = Object.assign({},ppt_p_176, (styles["para1"] || {}));
ppt_p_176.bullet = true;
ppt_p_176.color = "FF0000";
ppt_p_176.x = "10%";
ppt_p_176.y = "44%";
ppt_p_176.w ="80%";
ppt_p_176.isTextBox = true;
ppt_slide_171.addText(ppt_p_176_text, ppt_p_176);
ppt_slide_171_debug.items.push({ text: ppt_p_176_text, options: ppt_p_176 });
var ppt_p_177 = Object.assign({}, defaultStyle.content);
const ppt_p_177_text = "Le modalità di lettura";
ppt_p_177 = Object.assign({},ppt_p_177, (styles["para1"] || {}));
ppt_p_177.bullet = true;
ppt_p_177.color = "FF0000";
ppt_p_177.x = "10%";
ppt_p_177.y = "54%";
ppt_p_177.w ="80%";
ppt_p_177.isTextBox = true;
ppt_slide_171.addText(ppt_p_177_text, ppt_p_177);
ppt_slide_171_debug.items.push({ text: ppt_p_177_text, options: ppt_p_177 });
var ppt_p_178 = Object.assign({}, defaultStyle.content);
const ppt_p_178_text = "Frequentare la biblioteca";
ppt_p_178 = Object.assign({},ppt_p_178, (styles["para1"] || {}));
ppt_p_178.bullet = true;
ppt_p_178.color = "FF0000";
ppt_p_178.x = "10%";
ppt_p_178.y = "64%";
ppt_p_178.w ="80%";
ppt_p_178.isTextBox = true;
ppt_slide_171.addText(ppt_p_178_text, ppt_p_178);
ppt_slide_171_debug.items.push({ text: ppt_p_178_text, options: ppt_p_178 });
var ppt_p_179 = Object.assign({}, defaultStyle.content);
const ppt_p_179_text = "Frequentare le librerie";
ppt_p_179 = Object.assign({},ppt_p_179, (styles["para1"] || {}));
ppt_p_179.bullet = true;
ppt_p_179.color = "FF0000";
ppt_p_179.x = "10%";
ppt_p_179.y = "74%";
ppt_p_179.w ="80%";
ppt_p_179.isTextBox = true;
ppt_slide_171.addText(ppt_p_179_text, ppt_p_179);
ppt_slide_171_debug.items.push({ text: ppt_p_179_text, options: ppt_p_179 });
ppt_doc_1_debug.slides.push(ppt_slide_171_debug);
const ppt_slide_180 = ppt_doc_1.addSlide();
const ppt_slide_180_debug = { items: [] };
var ppt_p_181 = Object.assign({}, defaultStyle.content);
const ppt_p_181_text = "NpL e NpM";
ppt_p_181 = Object.assign({},ppt_p_181, (styles["titolo1"] || {}));
ppt_p_181.isTextBox = true;
ppt_slide_180.addText(ppt_p_181_text, ppt_p_181);
ppt_slide_180_debug.items.push({ text: ppt_p_181_text, options: ppt_p_181 });
var ppt_p_182 = Object.assign({}, defaultStyle.content);
const ppt_p_182_text = "3 anni e 6 mesi, Papà";
ppt_p_182 = Object.assign({},ppt_p_182, (styles["titolo2"] || {}));
ppt_p_182.isTextBox = true;
ppt_slide_180.addText(ppt_p_182_text, ppt_p_182);
ppt_slide_180_debug.items.push({ text: ppt_p_182_text, options: ppt_p_182 });
const ppt_image_183 = {};
ppt_image_183.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_183.x = "20%";
ppt_image_183.y = "24%";
ppt_image_183.w ="29%";
ppt_image_183.h ="74%";
ppt_slide_180.addImage(ppt_image_183);
ppt_slide_180_debug.items.push({ image: ppt_image_183 });
const ppt_image_184 = {};
ppt_image_184.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/NpL 2.png";
ppt_image_184.x = "23%";
ppt_image_184.y = "31%";
ppt_image_184.w ="23%";
ppt_image_184.h ="63%";
ppt_slide_180.addImage(ppt_image_184);
ppt_slide_180_debug.items.push({ image: ppt_image_184 });
ppt_doc_1_debug.slides.push(ppt_slide_180_debug);
const ppt_slide_185 = ppt_doc_1.addSlide();
const ppt_slide_185_debug = { items: [] };
var ppt_p_186 = Object.assign({}, defaultStyle.content);
const ppt_p_186_text = "NpL e NpM";
ppt_p_186 = Object.assign({},ppt_p_186, (styles["titolo1"] || {}));
ppt_p_186.isTextBox = true;
ppt_slide_185.addText(ppt_p_186_text, ppt_p_186);
ppt_slide_185_debug.items.push({ text: ppt_p_186_text, options: ppt_p_186 });
var ppt_p_187 = Object.assign({}, defaultStyle.content);
const ppt_p_187_text = "4 anni, Dialogico";
ppt_p_187 = Object.assign({},ppt_p_187, (styles["titolo2"] || {}));
ppt_p_187.isTextBox = true;
ppt_slide_185.addText(ppt_p_187_text, ppt_p_187);
ppt_slide_185_debug.items.push({ text: ppt_p_187_text, options: ppt_p_187 });
const ppt_image_188 = {};
ppt_image_188.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/iphone.png";
ppt_image_188.x = "20%";
ppt_image_188.y = "24%";
ppt_image_188.w ="29%";
ppt_image_188.h ="74%";
ppt_slide_185.addImage(ppt_image_188);
ppt_slide_185_debug.items.push({ image: ppt_image_188 });
const ppt_image_189 = {};
ppt_image_189.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/NpL 3.png";
ppt_image_189.x = "23%";
ppt_image_189.y = "31%";
ppt_image_189.w ="23%";
ppt_image_189.h ="63%";
ppt_slide_185.addImage(ppt_image_189);
ppt_slide_185_debug.items.push({ image: ppt_image_189 });
ppt_doc_1_debug.slides.push(ppt_slide_185_debug);
const ppt_slide_190 = ppt_doc_1.addSlide();
const ppt_slide_190_debug = { items: [] };
var ppt_p_191 = Object.assign({}, defaultStyle.content);
const ppt_p_191_text = "La App BeBa, un lavoro da implementare";
ppt_p_191 = Object.assign({},ppt_p_191, (styles["titolo1"] || {}));
ppt_p_191.isTextBox = true;
ppt_slide_190.addText(ppt_p_191_text, ppt_p_191);
ppt_slide_190_debug.items.push({ text: ppt_p_191_text, options: ppt_p_191 });
var ppt_p_192 = Object.assign({}, defaultStyle.content);
const ppt_p_192_text = " ";
ppt_p_192 = Object.assign({},ppt_p_192, (styles["titolo2"] || {}));
ppt_p_192.isTextBox = true;
ppt_slide_190.addText(ppt_p_192_text, ppt_p_192);
ppt_slide_190_debug.items.push({ text: ppt_p_192_text, options: ppt_p_192 });
var ppt_p_193 = Object.assign({}, defaultStyle.content);
const ppt_p_193_text = " ";
ppt_p_193 = Object.assign({},ppt_p_193, (styles[".column-title"] || {}));
ppt_p_193.x = "10%";
ppt_p_193.y = "24%";
ppt_p_193.w ="40%";
ppt_p_193.breakLine = true;
ppt_p_193.isTextBox = true;
ppt_slide_190.addText(ppt_p_193_text, ppt_p_193);
ppt_slide_190_debug.items.push({ text: ppt_p_193_text, options: ppt_p_193 });
var ppt_p_194 = Object.assign({}, defaultStyle.content);
const ppt_p_194_text = "Con i feedback dei genitori";
ppt_p_194 = Object.assign({},ppt_p_194, (styles[".column-p-big"] || {}));
ppt_p_194.x = "10%";
ppt_p_194.y = "32%";
ppt_p_194.w ="40%";
ppt_p_194.breakLine = true;
ppt_p_194.isTextBox = true;
ppt_slide_190.addText(ppt_p_194_text, ppt_p_194);
ppt_slide_190_debug.items.push({ text: ppt_p_194_text, options: ppt_p_194 });
var ppt_p_195 = Object.assign({}, defaultStyle.content);
const ppt_p_195_text = " ";
ppt_p_195 = Object.assign({},ppt_p_195, (styles[".column-title"] || {}));
ppt_p_195.x = "10%";
ppt_p_195.y = "44%";
ppt_p_195.w ="40%";
ppt_p_195.breakLine = true;
ppt_p_195.isTextBox = true;
ppt_slide_190.addText(ppt_p_195_text, ppt_p_195);
ppt_slide_190_debug.items.push({ text: ppt_p_195_text, options: ppt_p_195 });
var ppt_p_196 = Object.assign({}, defaultStyle.content);
const ppt_p_196_text = "Con i feedback dei pediatri";
ppt_p_196 = Object.assign({},ppt_p_196, (styles[".column-p-big"] || {}));
ppt_p_196.x = "10%";
ppt_p_196.y = "52%";
ppt_p_196.w ="40%";
ppt_p_196.breakLine = true;
ppt_p_196.isTextBox = true;
ppt_slide_190.addText(ppt_p_196_text, ppt_p_196);
ppt_slide_190_debug.items.push({ text: ppt_p_196_text, options: ppt_p_196 });
const ppt_image_197 = {};
ppt_image_197.path = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/work in progress.png";
ppt_image_197.y = "34%";
ppt_image_197.x = "55%";
ppt_image_197.w ="32%";
ppt_image_197.h ="35%";
ppt_slide_190.addImage(ppt_image_197);
ppt_slide_190_debug.items.push({ image: ppt_image_197 });
ppt_doc_1_debug.slides.push(ppt_slide_190_debug);
const ppt_slide_198 = ppt_doc_1.addSlide();
const ppt_slide_198_debug = { items: [] };
var ppt_p_199 = Object.assign({}, defaultStyle.content);
const ppt_p_199_text = "Grazie";
ppt_p_199 = Object.assign({},ppt_p_199, (styles[".thanks-title"] || {}));
ppt_p_199.y = "30%";
ppt_p_199.isTextBox = true;
ppt_slide_198.addText(ppt_p_199_text, ppt_p_199);
ppt_slide_198_debug.items.push({ text: ppt_p_199_text, options: ppt_p_199 });
var ppt_p_200 = Object.assign({}, defaultStyle.content);
const ppt_p_200_text = "per l'attenzione";
ppt_p_200 = Object.assign({},ppt_p_200, (styles[".thanks-subtitle"] || {}));
ppt_p_200.y = "50%";
ppt_p_200.isTextBox = true;
ppt_slide_198.addText(ppt_p_200_text, ppt_p_200);
ppt_slide_198_debug.items.push({ text: ppt_p_200_text, options: ppt_p_200 });
ppt_doc_1_debug.slides.push(ppt_slide_198_debug);

// Dump for test
    fs.writeFileSync(__dirname + "/presentazione_marzo_21.ppt.json", JSON.stringify(ppt_doc_1_debug, null, "	"));

// Make Ppt

var now = new Date();

ppt_doc_1.writeFile(
    __dirname + "/presentazione_marzo_21.ppt"
).then(fileName => {
    console.log(`created file: ${fileName}`);
    console.log("DONE written", new Date() - now)
});
