const fs = require("fs");
const pdfmake = require("pdfmake");

const pdf_doc_1 = { content: [], styles: {} };
const pdf_styleDef_2 = {};
pdf_styleDef_2.fontSize = 60;
pdf_styleDef_2.margin = [0,150,0,0];
pdf_styleDef_2.bold = true;
pdf_doc_1.styles[".forefront-title"] = pdf_styleDef_2;
const pdf_styleDef_3 = {};
pdf_styleDef_3.fontSize = 40;
pdf_styleDef_3.margin = [0,10,0,0];
pdf_styleDef_3.italics = true;
pdf_doc_1.styles[".forefront-subtitle"] = pdf_styleDef_3;
const pdf_styleDef_4 = {};
pdf_styleDef_4.fontSize = 15;
pdf_styleDef_4.margin = [0,80,0,0];
pdf_doc_1.styles[".forefront-author"] = pdf_styleDef_4;
const pdf_styleDef_5 = {};
pdf_styleDef_5.fontSize = 10;
pdf_styleDef_5.margin = [0,20,0,0];
pdf_styleDef_5.italics = true;
pdf_doc_1.styles[".forefront-date"] = pdf_styleDef_5;
const pdf_styleDef_6 = {};
pdf_styleDef_6.fontSize = 40;
pdf_styleDef_6.bold = true;
pdf_styleDef_6.italics = true;
pdf_styleDef_6.color = "#e02424";
pdf_styleDef_6.alignment = "right";
pdf_styleDef_6.margin = [0,20,0,20];
pdf_doc_1.styles["titolo1"] = pdf_styleDef_6;
const pdf_styleDef_7 = {};
pdf_styleDef_7.fontSize = 30;
pdf_styleDef_7.bold = true;
pdf_styleDef_7.italics = true;
pdf_styleDef_7.color = "#020202";
pdf_styleDef_7.alignment = "left";
pdf_styleDef_7.margin = [0,10,0,10];
pdf_doc_1.styles["titolo2"] = pdf_styleDef_7;
const pdf_styleDef_8 = {};
pdf_styleDef_8.fontSize = 15;
pdf_styleDef_8.alignment = "left";
pdf_styleDef_8.margin = [0,20,0,0];
pdf_doc_1.styles["para1"] = pdf_styleDef_8;
const pdf_styleDef_9 = {};
pdf_styleDef_9.fontSize = 37.5;
pdf_styleDef_9.alignment = "left";
pdf_styleDef_9.margin = [0,20,0,0];
pdf_doc_1.styles["para1big"] = pdf_styleDef_9;
const pdf_styleDef_10 = {};
pdf_styleDef_10.margin = [0,10,0,0];
pdf_doc_1.styles[".cite-reviews"] = pdf_styleDef_10;
const pdf_styleDef_11 = {};
pdf_styleDef_11.fontSize = 10;
pdf_styleDef_11.alignment = "left";
pdf_styleDef_11.bold = true;
pdf_styleDef_11.margin = [0,10,0,0];
pdf_doc_1.styles[".cite-article"] = pdf_styleDef_11;
const pdf_styleDef_12 = {};
pdf_styleDef_12.fontSize = 10;
pdf_styleDef_12.italics = true;
pdf_styleDef_12.alignment = "left";
pdf_doc_1.styles[".cite-authors"] = pdf_styleDef_12;
const pdf_styleDef_13 = {};
pdf_styleDef_13.fontSize = 10;
pdf_styleDef_13.italics = true;
pdf_styleDef_13.alignment = "left";
pdf_doc_1.styles[".cite-review"] = pdf_styleDef_13;
const pdf_styleDef_14 = {};
pdf_styleDef_14.fontSize = 60;
pdf_styleDef_14.margin = [0,200,0,0];
pdf_styleDef_14.alignment = "center";
pdf_styleDef_14.color = "#e02424";
pdf_styleDef_14.bold = true;
pdf_doc_1.styles[".thanks-title"] = pdf_styleDef_14;
const pdf_styleDef_15 = {};
pdf_styleDef_15.fontSize = 48;
pdf_styleDef_15.margin = [0,20,0,0];
pdf_styleDef_15.alignment = "center";
pdf_styleDef_15.color = "#e02424";
pdf_styleDef_15.bold = true;
pdf_doc_1.styles[".thanks-subtitle"] = pdf_styleDef_15;
const pdf_styleDef_16 = {};
pdf_styleDef_16.fontSize = 16;
pdf_styleDef_16.margin = [0,20,0,0];
pdf_styleDef_16.bold = true;
pdf_doc_1.styles[".column-title"] = pdf_styleDef_16;
const pdf_styleDef_17 = {};
pdf_styleDef_17.fontSize = 14;
pdf_styleDef_17.margin = [0,10,0,0];
pdf_doc_1.styles[".column-p"] = pdf_styleDef_17;
const pdf_styleDef_18 = {};
pdf_styleDef_18.fontSize = 28;
pdf_styleDef_18.margin = [0,10,0,0];
pdf_doc_1.styles[".column-p-big"] = pdf_styleDef_18;
const pdf_sect_19 = { content: [], styles: {} };
const pdf_p_20 = {};
pdf_p_20.text = [];
pdf_p_20.text.push("Le guide anticipatorie");
pdf_p_20.style = ".forefront-title";
pdf_sect_19["content"].push(pdf_p_20);
const pdf_p_21 = {};
pdf_p_21.text = [];
pdf_p_21.text.push("Tutti a tavola");
pdf_p_21.style = ".forefront-subtitle";
pdf_sect_19["content"].push(pdf_p_21);
const pdf_p_22 = {};
pdf_p_22.text = [];
pdf_p_22.text.push("Nati per leggere");
pdf_p_22.style = ".forefront-subtitle";
pdf_sect_19["content"].push(pdf_p_22);
const pdf_p_23 = {};
pdf_p_23.text = [];
pdf_p_23.text.push("Anna Maria Davoli");
pdf_p_23.style = ".forefront-author";
pdf_sect_19["content"].push(pdf_p_23);
const pdf_p_24 = {};
pdf_p_24.text = [];
pdf_p_24.text.push("17 marzo 2021");
pdf_p_24.style = ".forefront-date";
pdf_sect_19["content"].push(pdf_p_24);
const pdf_MainObject = { sections : [] };
pdf_sect_19.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_19);
const pdf_sect_25 = { content: [], styles: {} };
const pdf_p_26 = {};
pdf_p_26.text = [];
pdf_p_26.style = "titolo1";
pdf_sect_25["content"].push(pdf_p_26);
const pdf_p_27 = {};
pdf_p_27.text = [];
pdf_p_27.text.push("Le App a supporto di genitori e caregiver");
pdf_p_27.style = "titolo2";
pdf_sect_25["content"].push(pdf_p_27);
const pdf_ul_28 = {};
pdf_ul_28.ul = [];
const pdf_p_29 = {};
pdf_p_29.text = [];
pdf_p_29.text.push("Contenuti basati sulle evidenze");
pdf_p_29.style = "para1";
pdf_ul_28["ul"].push(pdf_p_29);
const pdf_p_30 = {};
pdf_p_30.text = [];
pdf_p_30.text.push("Informazioni coerenti con le linee guida");
pdf_p_30.style = "para1";
pdf_ul_28["ul"].push(pdf_p_30);
const pdf_p_31 = {};
pdf_p_31.text = [];
pdf_p_31.text.push("Sviluppate con il supporto di professionisti sanitari");
pdf_p_31.style = "para1";
pdf_ul_28["ul"].push(pdf_p_31);
const pdf_p_32 = {};
pdf_p_32.text = [];
pdf_p_32.text.push("Con finanziamento adeguato (del Servizio Sanitario)");
pdf_p_32.style = "para1";
pdf_ul_28["ul"].push(pdf_p_32);
pdf_sect_25["content"].push(pdf_ul_28);
const pdf_p_33 = {};
pdf_p_33.text = [];
pdf_p_33.text.push("Garantiscono che ai genitori vengano fornite risorse credibili e affidabili.");
pdf_p_33.style = "para1";
pdf_sect_25["content"].push(pdf_p_33);
const pdf_stack_34 = {};
pdf_stack_34.stack = [];
pdf_stack_34.style = ".cite-reviews";
const pdf_p_35 = {};
pdf_p_35.text = [];
pdf_p_35.text.push("Content and Quality of Infant Feeding Smartphone Apps: Five-Year Update on a Systematic Search and Evaluation");
pdf_p_35.style = ".cite-article";
pdf_stack_34["stack"].push(pdf_p_35);
const pdf_p_36 = {};
pdf_p_36.text = [];
pdf_p_36.text.push("Heilok Cheng, et all");
pdf_p_36.style = ".cite-authors";
pdf_stack_34["stack"].push(pdf_p_36);
const pdf_p_37 = {};
pdf_p_37.text = [];
pdf_p_37.text.push("A Mobile App, KhunLook, to Support Thai Parents and Caregivers With Child Health Supervision: Development, Validation, and Acceptability Study");
pdf_p_37.style = ".cite-article";
pdf_stack_34["stack"].push(pdf_p_37);
const pdf_p_38 = {};
pdf_p_38.text = [];
pdf_p_38.text.push("Rosawan Areemit");
pdf_p_38.style = ".cite-authors";
pdf_stack_34["stack"].push(pdf_p_38);
pdf_sect_25["content"].push(pdf_stack_34);
pdf_sect_25.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_25);
const pdf_sect_39 = { content: [], styles: {} };
const pdf_p_40 = {};
pdf_p_40.text = [];
pdf_p_40.style = "titolo1";
pdf_sect_39["content"].push(pdf_p_40);
const pdf_p_41 = {};
pdf_p_41.text = [];
pdf_p_41.text.push("Una App aiuta i genitori?");
pdf_p_41.style = "titolo2";
pdf_sect_39["content"].push(pdf_p_41);
const pdf_p_42 = {};
pdf_p_42.text = [];
pdf_p_42.text.push("I genitori apprezzano le mHealth Apps.");
pdf_p_42.style = "para1";
pdf_sect_39["content"].push(pdf_p_42);
const pdf_p_43 = {};
pdf_p_43.text = [];
pdf_p_43.text.push("Richiedono contatti brevi e ripetuti con informazioni pratiche.");
pdf_p_43.style = "para1";
pdf_sect_39["content"].push(pdf_p_43);
const pdf_p_44 = {};
pdf_p_44.text = [];
pdf_p_44.text.push("Un programma eHealth di prevenzione dell'obesità infantile incentrato sui genitori può fornire supporto per migliorare l'alimentazione del bambino e l'autoefficacia parentale.");
pdf_p_44.style = "para1";
pdf_sect_39["content"].push(pdf_p_44);
const pdf_stack_45 = {};
pdf_stack_45.stack = [];
pdf_stack_45.style = ".cite-reviews";
const pdf_p_46 = {};
pdf_p_46.text = [];
pdf_p_46.text.push("A Mobile App, KhunLook, to Support Thai Parents and Caregivers With Child Health Supervision: Development, Validation, and Acceptability Study");
pdf_p_46.style = ".cite-article";
pdf_stack_45["stack"].push(pdf_p_46);
const pdf_p_47 = {};
pdf_p_47.text = [];
pdf_p_47.text.push("Rosawan Areemit et all");
pdf_p_47.style = ".cite-authors";
pdf_stack_45["stack"].push(pdf_p_47);
const pdf_p_48 = {};
pdf_p_48.text = [];
pdf_p_48.text.push("An Internet-Based Childhood Obesity Prevention Program (Time2bHealthy) for Parents of Preschool-Aged Children.");
pdf_p_48.style = ".cite-article";
pdf_stack_45["stack"].push(pdf_p_48);
const pdf_p_49 = {};
pdf_p_49.text = [];
pdf_p_49.text.push("Megan L Hammersley et all");
pdf_p_49.style = ".cite-authors";
pdf_stack_45["stack"].push(pdf_p_49);
const pdf_p_50 = {};
pdf_p_50.text = [];
pdf_p_50.text.push("Randomized Controlled Trial J Med Internet Res, 2019 Feb 8;21(2):e11964. Doi: 10.2196/11964.");
pdf_p_50.style = ".cite-review";
pdf_stack_45["stack"].push(pdf_p_50);
const pdf_p_51 = {};
pdf_p_51.text = [];
pdf_p_51.text.push("A systematic evaluation of digital nutrition promotion websites and apps for supporting parents to influence children’s nutrition");
pdf_p_51.style = ".cite-article";
pdf_stack_45["stack"].push(pdf_p_51);
const pdf_p_52 = {};
pdf_p_52.text = [];
pdf_p_52.text.push("Dorota Zarnowiecki, et all");
pdf_p_52.style = ".cite-authors";
pdf_stack_45["stack"].push(pdf_p_52);
const pdf_p_53 = {};
pdf_p_53.text = [];
pdf_p_53.text.push("International Journal of Behavioral Nutrition and Physical Activity volume 17, Article number: 17 (2020)");
pdf_p_53.style = ".cite-review";
pdf_stack_45["stack"].push(pdf_p_53);
pdf_sect_39["content"].push(pdf_stack_45);
pdf_sect_39.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_39);
const pdf_sect_54 = { content: [], styles: {} };
const pdf_p_55 = {};
pdf_p_55.text = [];
pdf_p_55.text.push("Tutti a tavola");
pdf_p_55.style = "titolo1";
pdf_sect_54["content"].push(pdf_p_55);
const pdf_p_56 = {};
pdf_p_56.text = [];
pdf_p_56.text.push("nascita");
pdf_p_56.style = "titolo2";
pdf_sect_54["content"].push(pdf_p_56);
const pdf_image_57 = {};
pdf_image_57.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/nascita.png";
pdf_image_57.width = 300;
pdf_image_57.height = 550;
pdf_sect_54["content"].push(pdf_image_57);
pdf_sect_54.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_54);
const pdf_sect_58 = { content: [], styles: {} };
const pdf_p_59 = {};
pdf_p_59.text = [];
pdf_p_59.text.push("Tutti a tavola");
pdf_p_59.style = "titolo1";
pdf_sect_58["content"].push(pdf_p_59);
const pdf_p_60 = {};
pdf_p_60.text = [];
pdf_p_60.text.push("15 giorni");
pdf_p_60.style = "titolo2";
pdf_sect_58["content"].push(pdf_p_60);
const pdf_image_61 = {};
pdf_image_61.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/15 giorni.png";
pdf_image_61.width = 300;
pdf_image_61.height = 550;
pdf_sect_58["content"].push(pdf_image_61);
pdf_sect_58.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_58);
const pdf_sect_62 = { content: [], styles: {} };
const pdf_p_63 = {};
pdf_p_63.text = [];
pdf_p_63.text.push("Tutti a tavola");
pdf_p_63.style = "titolo1";
pdf_sect_62["content"].push(pdf_p_63);
const pdf_p_64 = {};
pdf_p_64.text = [];
pdf_p_64.text.push("1 mese");
pdf_p_64.style = "titolo2";
pdf_sect_62["content"].push(pdf_p_64);
const pdf_image_65 = {};
pdf_image_65.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/1 mese.png";
pdf_image_65.width = 300;
pdf_image_65.height = 550;
pdf_sect_62["content"].push(pdf_image_65);
pdf_sect_62.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_62);
const pdf_sect_66 = { content: [], styles: {} };
const pdf_p_67 = {};
pdf_p_67.text = [];
pdf_p_67.text.push("Tutti a tavola");
pdf_p_67.style = "titolo1";
pdf_sect_66["content"].push(pdf_p_67);
const pdf_p_68 = {};
pdf_p_68.text = [];
pdf_p_68.text.push("5 mesi");
pdf_p_68.style = "titolo2";
pdf_sect_66["content"].push(pdf_p_68);
const pdf_image_69 = {};
pdf_image_69.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/5 mesi.png";
pdf_image_69.width = 300;
pdf_image_69.height = 550;
pdf_sect_66["content"].push(pdf_image_69);
pdf_sect_66.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_66);
const pdf_sect_70 = { content: [], styles: {} };
const pdf_p_71 = {};
pdf_p_71.text = [];
pdf_p_71.text.push("Tutti a tavola");
pdf_p_71.style = "titolo1";
pdf_sect_70["content"].push(pdf_p_71);
const pdf_p_72 = {};
pdf_p_72.text = [];
pdf_p_72.text.push("6 mesi");
pdf_p_72.style = "titolo2";
pdf_sect_70["content"].push(pdf_p_72);
const pdf_image_73 = {};
pdf_image_73.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/6 mesi.png";
pdf_image_73.width = 300;
pdf_image_73.height = 550;
pdf_sect_70["content"].push(pdf_image_73);
pdf_sect_70.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_70);
const pdf_sect_74 = { content: [], styles: {} };
const pdf_p_75 = {};
pdf_p_75.text = [];
pdf_p_75.text.push("Tutti a tavola");
pdf_p_75.style = "titolo1";
pdf_sect_74["content"].push(pdf_p_75);
const pdf_p_76 = {};
pdf_p_76.text = [];
pdf_p_76.text.push("9 mesi/1");
pdf_p_76.style = "titolo2";
pdf_sect_74["content"].push(pdf_p_76);
const pdf_image_77 = {};
pdf_image_77.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/9 mesi 1.png";
pdf_image_77.width = 300;
pdf_image_77.height = 550;
pdf_sect_74["content"].push(pdf_image_77);
pdf_sect_74.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_74);
const pdf_sect_78 = { content: [], styles: {} };
const pdf_p_79 = {};
pdf_p_79.text = [];
pdf_p_79.text.push("Tutti a tavola");
pdf_p_79.style = "titolo1";
pdf_sect_78["content"].push(pdf_p_79);
const pdf_p_80 = {};
pdf_p_80.text = [];
pdf_p_80.text.push("9 mesi/2");
pdf_p_80.style = "titolo2";
pdf_sect_78["content"].push(pdf_p_80);
const pdf_image_81 = {};
pdf_image_81.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/9 mesi 2.png";
pdf_image_81.width = 300;
pdf_image_81.height = 550;
pdf_sect_78["content"].push(pdf_image_81);
pdf_sect_78.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_78);
const pdf_sect_82 = { content: [], styles: {} };
const pdf_p_83 = {};
pdf_p_83.text = [];
pdf_p_83.text.push("Tutti a tavola");
pdf_p_83.style = "titolo1";
pdf_sect_82["content"].push(pdf_p_83);
const pdf_p_84 = {};
pdf_p_84.text = [];
pdf_p_84.text.push("1 anno");
pdf_p_84.style = "titolo2";
pdf_sect_82["content"].push(pdf_p_84);
const pdf_image_85 = {};
pdf_image_85.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/1 anno.png";
pdf_image_85.width = 300;
pdf_image_85.height = 550;
pdf_sect_82["content"].push(pdf_image_85);
pdf_sect_82.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_82);
const pdf_sect_86 = { content: [], styles: {} };
const pdf_p_87 = {};
pdf_p_87.text = [];
pdf_p_87.text.push("Tutti a tavola");
pdf_p_87.style = "titolo1";
pdf_sect_86["content"].push(pdf_p_87);
const pdf_p_88 = {};
pdf_p_88.text = [];
pdf_p_88.text.push("14 mesi");
pdf_p_88.style = "titolo2";
pdf_sect_86["content"].push(pdf_p_88);
const pdf_image_89 = {};
pdf_image_89.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/14 mesi.png";
pdf_image_89.width = 300;
pdf_image_89.height = 550;
pdf_sect_86["content"].push(pdf_image_89);
pdf_sect_86.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_86);
const pdf_sect_90 = { content: [], styles: {} };
const pdf_p_91 = {};
pdf_p_91.text = [];
pdf_p_91.text.push("Tutti a tavola");
pdf_p_91.style = "titolo1";
pdf_sect_90["content"].push(pdf_p_91);
const pdf_p_92 = {};
pdf_p_92.text = [];
pdf_p_92.text.push("17 mesi 1");
pdf_p_92.style = "titolo2";
pdf_sect_90["content"].push(pdf_p_92);
const pdf_image_93 = {};
pdf_image_93.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/17 m 1.png";
pdf_image_93.width = 300;
pdf_image_93.height = 550;
pdf_sect_90["content"].push(pdf_image_93);
pdf_sect_90.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_90);
const pdf_sect_94 = { content: [], styles: {} };
const pdf_p_95 = {};
pdf_p_95.text = [];
pdf_p_95.text.push("Tutti a tavola");
pdf_p_95.style = "titolo1";
pdf_sect_94["content"].push(pdf_p_95);
const pdf_p_96 = {};
pdf_p_96.text = [];
pdf_p_96.text.push("17 mesi 2");
pdf_p_96.style = "titolo2";
pdf_sect_94["content"].push(pdf_p_96);
const pdf_image_97 = {};
pdf_image_97.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/17 m 2.png";
pdf_image_97.width = 300;
pdf_image_97.height = 550;
pdf_sect_94["content"].push(pdf_image_97);
pdf_sect_94.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_94);
const pdf_sect_98 = { content: [], styles: {} };
const pdf_p_99 = {};
pdf_p_99.text = [];
pdf_p_99.text.push("Tutti a tavola");
pdf_p_99.style = "titolo1";
pdf_sect_98["content"].push(pdf_p_99);
const pdf_p_100 = {};
pdf_p_100.text = [];
pdf_p_100.text.push("18 mesi");
pdf_p_100.style = "titolo2";
pdf_sect_98["content"].push(pdf_p_100);
const pdf_image_101 = {};
pdf_image_101.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/18 mesi.png";
pdf_image_101.width = 300;
pdf_image_101.height = 550;
pdf_sect_98["content"].push(pdf_image_101);
pdf_sect_98.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_98);
const pdf_sect_102 = { content: [], styles: {} };
const pdf_p_103 = {};
pdf_p_103.text = [];
pdf_p_103.text.push("Tutti a tavola");
pdf_p_103.style = "titolo1";
pdf_sect_102["content"].push(pdf_p_103);
const pdf_p_104 = {};
pdf_p_104.text = [];
pdf_p_104.text.push("19 mesi");
pdf_p_104.style = "titolo2";
pdf_sect_102["content"].push(pdf_p_104);
const pdf_image_105 = {};
pdf_image_105.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/19 mesi.png";
pdf_image_105.width = 300;
pdf_image_105.height = 550;
pdf_sect_102["content"].push(pdf_image_105);
pdf_sect_102.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_102);
const pdf_sect_106 = { content: [], styles: {} };
const pdf_p_107 = {};
pdf_p_107.text = [];
pdf_p_107.text.push("Tutti a tavola");
pdf_p_107.style = "titolo1";
pdf_sect_106["content"].push(pdf_p_107);
const pdf_p_108 = {};
pdf_p_108.text = [];
pdf_p_108.text.push(" ");
pdf_p_108.style = "titolo2";
pdf_sect_106["content"].push(pdf_p_108);
const pdf_columns_109 = {};
pdf_columns_109.columns = [];
const pdf_stack_110 = {};
pdf_stack_110.stack = [];
const pdf_p_111 = {};
pdf_p_111.text = [];
pdf_p_111.text.push("20 mesi");
pdf_p_111.style = ".column-title";
pdf_stack_110["stack"].push(pdf_p_111);
const pdf_p_112 = {};
pdf_p_112.text = [];
pdf_p_112.text.push("Gli inquinanti alimentari");
pdf_p_112.style = ".column-p";
pdf_stack_110["stack"].push(pdf_p_112);
const pdf_p_113 = {};
pdf_p_113.text = [];
pdf_p_113.text.push("21 mesi");
pdf_p_113.style = ".column-title";
pdf_stack_110["stack"].push(pdf_p_113);
const pdf_p_114 = {};
pdf_p_114.text = [];
pdf_p_114.text.push("I pericoli in cucina");
pdf_p_114.style = ".column-p";
pdf_stack_110["stack"].push(pdf_p_114);
const pdf_p_115 = {};
pdf_p_115.text = [];
pdf_p_115.text.push("22 mesi");
pdf_p_115.style = ".column-title";
pdf_stack_110["stack"].push(pdf_p_115);
const pdf_p_116 = {};
pdf_p_116.text = [];
pdf_p_116.text.push("Il bisogno di fibre");
pdf_p_116.style = ".column-p";
pdf_stack_110["stack"].push(pdf_p_116);
const pdf_p_117 = {};
pdf_p_117.text = [];
pdf_p_117.text.push("2 anni");
pdf_p_117.style = ".column-title";
pdf_stack_110["stack"].push(pdf_p_117);
const pdf_p_118 = {};
pdf_p_118.text = [];
pdf_p_118.text.push("Buone abitudini e strategie per invogliare il tuo bambino a mangiare cibi salutari");
pdf_p_118.style = ".column-p";
pdf_stack_110["stack"].push(pdf_p_118);
const pdf_p_119 = {};
pdf_p_119.text = [];
pdf_p_119.text.push("3 anni e 2 mesi");
pdf_p_119.style = ".column-title";
pdf_stack_110["stack"].push(pdf_p_119);
const pdf_p_120 = {};
pdf_p_120.text = [];
pdf_p_120.text.push("E se non vuole mangiare frutta e verdura?");
pdf_p_120.style = ".column-p";
pdf_stack_110["stack"].push(pdf_p_120);
pdf_columns_109["columns"].push(pdf_stack_110);
const pdf_stack_121 = {};
pdf_stack_121.stack = [];
const pdf_image_122 = {};
pdf_image_122.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/l'orto dei piccoli.jpg";
pdf_image_122.width = 150;
pdf_image_122.height = 180;
pdf_image_122.margin = [20,10,0,0];
pdf_stack_121["stack"].push(pdf_image_122);
const pdf_image_123 = {};
pdf_image_123.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/mangia i piselli.jpg";
pdf_image_123.width = 150;
pdf_image_123.height = 180;
pdf_image_123.margin = [20,10,0,0];
pdf_stack_121["stack"].push(pdf_image_123);
pdf_columns_109["columns"].push(pdf_stack_121);
pdf_sect_106["content"].push(pdf_columns_109);
pdf_sect_106.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_106);
const pdf_sect_124 = { content: [], styles: {} };
const pdf_p_125 = {};
pdf_p_125.text = [];
pdf_p_125.text.push("Tutti a tavola");
pdf_p_125.style = "titolo1";
pdf_sect_124["content"].push(pdf_p_125);
const pdf_p_126 = {};
pdf_p_126.text = [];
pdf_p_126.text.push(" ");
pdf_p_126.style = "titolo2";
pdf_sect_124["content"].push(pdf_p_126);
const pdf_columns_127 = {};
pdf_columns_127.columns = [];
const pdf_stack_128 = {};
pdf_stack_128.stack = [];
const pdf_p_129 = {};
pdf_p_129.text = [];
pdf_p_129.text.push("3 anni e 6 mesi");
pdf_p_129.style = ".column-title";
pdf_stack_128["stack"].push(pdf_p_129);
const pdf_p_130 = {};
pdf_p_130.text = [];
pdf_p_130.text.push("Cerca di rendere più sani i tuoi piatti preferiti.\n\n Leggere un libro aiuta a mangiare cibi sani.");
pdf_p_130.style = ".column-p";
pdf_stack_128["stack"].push(pdf_p_130);
const pdf_p_131 = {};
pdf_p_131.text = [];
pdf_p_131.text.push("4 anni e 6 mesi");
pdf_p_131.style = ".column-title";
pdf_stack_128["stack"].push(pdf_p_131);
const pdf_p_132 = {};
pdf_p_132.text = [];
pdf_p_132.text.push("Come fare per essere un modello sano?");
pdf_p_132.style = ".column-p";
pdf_stack_128["stack"].push(pdf_p_132);
const pdf_p_133 = {};
pdf_p_133.text = [];
pdf_p_133.text.push("5 anni e 3 mesi");
pdf_p_133.style = ".column-title";
pdf_stack_128["stack"].push(pdf_p_133);
const pdf_p_134 = {};
pdf_p_134.text = [];
pdf_p_134.text.push("Fra i 5 e i 6 anni sarà molto utile un Bilancio di salute dal tuo pediatra");
pdf_p_134.style = ".column-p";
pdf_stack_128["stack"].push(pdf_p_134);
pdf_columns_127["columns"].push(pdf_stack_128);
const pdf_stack_135 = {};
pdf_stack_135.stack = [];
const pdf_image_136 = {};
pdf_image_136.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/musi piatti.jpg";
pdf_image_136.width = 150;
pdf_image_136.height = 180;
pdf_image_136.margin = [20,10,0,0];
pdf_stack_135["stack"].push(pdf_image_136);
const pdf_image_137 = {};
pdf_image_137.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/è ora di mangiare sano.jpg";
pdf_image_137.width = 150;
pdf_image_137.height = 180;
pdf_image_137.margin = [20,10,0,0];
pdf_stack_135["stack"].push(pdf_image_137);
const pdf_image_138 = {};
pdf_image_138.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/bminforma.png";
pdf_image_138.width = 150;
pdf_image_138.height = 180;
pdf_image_138.margin = [20,10,0,0];
pdf_stack_135["stack"].push(pdf_image_138);
pdf_columns_127["columns"].push(pdf_stack_135);
pdf_sect_124["content"].push(pdf_columns_127);
pdf_sect_124.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_124);
const pdf_sect_139 = { content: [], styles: {} };
const pdf_p_140 = {};
pdf_p_140.text = [];
pdf_p_140.text.push("Tutti a tavola");
pdf_p_140.style = "titolo1";
pdf_sect_139["content"].push(pdf_p_140);
const pdf_p_141 = {};
pdf_p_141.text = [];
pdf_p_141.text.push("5 anni e 9 mesi/1");
pdf_p_141.style = "titolo2";
pdf_sect_139["content"].push(pdf_p_141);
const pdf_image_142 = {};
pdf_image_142.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/5a 9 m.png";
pdf_image_142.width = 300;
pdf_image_142.height = 550;
pdf_sect_139["content"].push(pdf_image_142);
pdf_sect_139.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_139);
const pdf_sect_143 = { content: [], styles: {} };
const pdf_p_144 = {};
pdf_p_144.text = [];
pdf_p_144.text.push("Tutti a tavola");
pdf_p_144.style = "titolo1";
pdf_sect_143["content"].push(pdf_p_144);
const pdf_p_145 = {};
pdf_p_145.text = [];
pdf_p_145.text.push("5 anni e 9 mesi/2");
pdf_p_145.style = "titolo2";
pdf_sect_143["content"].push(pdf_p_145);
const pdf_image_146 = {};
pdf_image_146.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/5a 9m 2.png";
pdf_image_146.width = 300;
pdf_image_146.height = 550;
pdf_sect_143["content"].push(pdf_image_146);
pdf_sect_143.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_143);
const pdf_sect_147 = { content: [], styles: {} };
const pdf_p_148 = {};
pdf_p_148.text = [];
pdf_p_148.text.push("Tutti a tavola");
pdf_p_148.style = "titolo1";
pdf_sect_147["content"].push(pdf_p_148);
const pdf_p_149 = {};
pdf_p_149.text = [];
pdf_p_149.text.push("6 anni");
pdf_p_149.style = "titolo2";
pdf_sect_147["content"].push(pdf_p_149);
const pdf_columns_150 = {};
pdf_columns_150.columns = [];
const pdf_stack_151 = {};
pdf_stack_151.stack = [];
const pdf_p_152 = {};
pdf_p_152.text = [];
pdf_p_152.style = ".column-title";
pdf_stack_151["stack"].push(pdf_p_152);
const pdf_p_153 = {};
pdf_p_153.text = [];
pdf_p_153.text.push("\n\n\n\n\n\n\n\nColtiva un piccolo orto domestico");
pdf_p_153.style = ".column-p";
pdf_stack_151["stack"].push(pdf_p_153);
pdf_columns_150["columns"].push(pdf_stack_151);
const pdf_stack_154 = {};
pdf_stack_154.stack = [];
const pdf_image_155 = {};
pdf_image_155.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/l'orto dei bimbi.jpg";
pdf_image_155.width = 150;
pdf_image_155.height = 180;
pdf_image_155.margin = [20,10,0,0];
pdf_stack_154["stack"].push(pdf_image_155);
const pdf_image_156 = {};
pdf_image_156.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/bimbi orticoltori.jpg";
pdf_image_156.width = 150;
pdf_image_156.height = 180;
pdf_image_156.margin = [20,10,0,0];
pdf_stack_154["stack"].push(pdf_image_156);
pdf_columns_150["columns"].push(pdf_stack_154);
pdf_sect_147["content"].push(pdf_columns_150);
pdf_sect_147.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_147);
const pdf_sect_157 = { content: [], styles: {} };
const pdf_p_158 = {};
pdf_p_158.text = [];
pdf_p_158.text.push("Tutti a tavola");
pdf_p_158.style = "titolo1";
pdf_sect_157["content"].push(pdf_p_158);
const pdf_p_159 = {};
pdf_p_159.text = [];
pdf_p_159.text.push(" ");
pdf_p_159.style = "titolo2";
pdf_sect_157["content"].push(pdf_p_159);
const pdf_columns_160 = {};
pdf_columns_160.columns = [];
const pdf_stack_161 = {};
pdf_stack_161.stack = [];
const pdf_p_162 = {};
pdf_p_162.text = [];
pdf_p_162.text.push("6 anni");
pdf_p_162.style = ".column-title";
pdf_stack_161["stack"].push(pdf_p_162);
const pdf_p_163 = {};
pdf_p_163.text = [];
pdf_p_163.text.push("\n\n\n\nDiventa un critico gastronomico...\n\n\n\n\n\n\n\n\n\n I momenti speciali a tavola uniscono la famiglia");
pdf_p_163.style = ".column-p";
pdf_stack_161["stack"].push(pdf_p_163);
pdf_columns_160["columns"].push(pdf_stack_161);
const pdf_stack_164 = {};
pdf_stack_164.stack = [];
const pdf_image_165 = {};
pdf_image_165.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/3 cuochi.jpg";
pdf_image_165.width = 150;
pdf_image_165.height = 180;
pdf_image_165.margin = [20,10,0,0];
pdf_stack_164["stack"].push(pdf_image_165);
const pdf_image_166 = {};
pdf_image_166.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/momenti speciali a tavola.jpg";
pdf_image_166.width = 150;
pdf_image_166.height = 180;
pdf_image_166.margin = [20,10,0,0];
pdf_stack_164["stack"].push(pdf_image_166);
pdf_columns_160["columns"].push(pdf_stack_164);
pdf_sect_157["content"].push(pdf_columns_160);
pdf_sect_157.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_157);
const pdf_sect_167 = { content: [], styles: {} };
const pdf_p_168 = {};
pdf_p_168.text = [];
pdf_p_168.text.push("NpL e NpM");
pdf_p_168.style = "titolo1";
pdf_sect_167["content"].push(pdf_p_168);
const pdf_p_169 = {};
pdf_p_169.text = [];
pdf_p_169.text.push(" ");
pdf_p_169.style = "titolo2";
pdf_sect_167["content"].push(pdf_p_169);
const pdf_p_170 = {};
pdf_p_170.text = [];
pdf_p_170.text.push("Proposte di libri e ascolti musicali per le varie età");
pdf_p_170.style = "para1";
pdf_sect_167["content"].push(pdf_p_170);
const pdf_p_171 = {};
pdf_p_171.text = [];
pdf_p_171.text.push("Consigli");
pdf_p_171.style = "para1";
pdf_sect_167["content"].push(pdf_p_171);
const pdf_ul_172 = {};
pdf_ul_172.ul = [];
const pdf_p_173 = {};
pdf_p_173.text = [];
pdf_p_173.text.push("Tanti libri di qualità per ogni età");
pdf_p_173.style = "para1";
pdf_ul_172["ul"].push(pdf_p_173);
const pdf_p_174 = {};
pdf_p_174.text = [];
pdf_p_174.text.push("Le modalità di lettura");
pdf_p_174.style = "para1";
pdf_ul_172["ul"].push(pdf_p_174);
const pdf_p_175 = {};
pdf_p_175.text = [];
pdf_p_175.text.push("Frequentare la biblioteca");
pdf_p_175.style = "para1";
pdf_ul_172["ul"].push(pdf_p_175);
const pdf_p_176 = {};
pdf_p_176.text = [];
pdf_p_176.text.push("Frequentare le librerie");
pdf_p_176.style = "para1";
pdf_ul_172["ul"].push(pdf_p_176);
pdf_sect_167["content"].push(pdf_ul_172);
pdf_sect_167.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_167);
const pdf_sect_177 = { content: [], styles: {} };
const pdf_p_178 = {};
pdf_p_178.text = [];
pdf_p_178.text.push("NpL e NpM");
pdf_p_178.style = "titolo1";
pdf_sect_177["content"].push(pdf_p_178);
const pdf_p_179 = {};
pdf_p_179.text = [];
pdf_p_179.text.push("3 anni e 6 mesi, Papà");
pdf_p_179.style = "titolo2";
pdf_sect_177["content"].push(pdf_p_179);
const pdf_image_180 = {};
pdf_image_180.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/NpL 2.png";
pdf_image_180.width = 300;
pdf_image_180.height = 550;
pdf_sect_177["content"].push(pdf_image_180);
pdf_sect_177.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_177);
const pdf_sect_181 = { content: [], styles: {} };
const pdf_p_182 = {};
pdf_p_182.text = [];
pdf_p_182.text.push("NpL e NpM");
pdf_p_182.style = "titolo1";
pdf_sect_181["content"].push(pdf_p_182);
const pdf_p_183 = {};
pdf_p_183.text = [];
pdf_p_183.text.push("4 anni, Dialogico");
pdf_p_183.style = "titolo2";
pdf_sect_181["content"].push(pdf_p_183);
const pdf_image_184 = {};
pdf_image_184.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/NpL 3.png";
pdf_image_184.width = 300;
pdf_image_184.height = 550;
pdf_sect_181["content"].push(pdf_image_184);
pdf_sect_181.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_181);
const pdf_sect_185 = { content: [], styles: {} };
const pdf_p_186 = {};
pdf_p_186.text = [];
pdf_p_186.text.push("La App BeBa, un lavoro da implementare");
pdf_p_186.style = "titolo1";
pdf_sect_185["content"].push(pdf_p_186);
const pdf_p_187 = {};
pdf_p_187.text = [];
pdf_p_187.text.push(" ");
pdf_p_187.style = "titolo2";
pdf_sect_185["content"].push(pdf_p_187);
const pdf_columns_188 = {};
pdf_columns_188.columns = [];
const pdf_stack_189 = {};
pdf_stack_189.stack = [];
const pdf_p_190 = {};
pdf_p_190.text = [];
pdf_p_190.text.push(" ");
pdf_p_190.style = ".column-title";
pdf_stack_189["stack"].push(pdf_p_190);
const pdf_p_191 = {};
pdf_p_191.text = [];
pdf_p_191.text.push("Con i feedback dei genitori");
pdf_p_191.style = ".column-p-big";
pdf_stack_189["stack"].push(pdf_p_191);
const pdf_p_192 = {};
pdf_p_192.text = [];
pdf_p_192.text.push(" ");
pdf_p_192.style = ".column-title";
pdf_stack_189["stack"].push(pdf_p_192);
const pdf_p_193 = {};
pdf_p_193.text = [];
pdf_p_193.text.push("Con i feedback dei pediatri");
pdf_p_193.style = ".column-p-big";
pdf_stack_189["stack"].push(pdf_p_193);
pdf_columns_188["columns"].push(pdf_stack_189);
const pdf_stack_194 = {};
pdf_stack_194.stack = [];
const pdf_image_195 = {};
pdf_image_195.image = "C:/My/wizzi/stfnbssl/wizzi.documents/packages/anna.beba/.wizzi-override/documents/marzo21/images/work in progress.png";
pdf_image_195.width = 150;
pdf_image_195.height = 180;
pdf_image_195.margin = [20,10,0,0];
pdf_stack_194["stack"].push(pdf_image_195);
pdf_columns_188["columns"].push(pdf_stack_194);
pdf_sect_185["content"].push(pdf_columns_188);
pdf_sect_185.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_185);
const pdf_sect_196 = { content: [], styles: {} };
const pdf_p_197 = {};
pdf_p_197.text = [];
pdf_p_197.text.push("Grazie");
pdf_p_197.style = ".thanks-title";
pdf_sect_196["content"].push(pdf_p_197);
const pdf_p_198 = {};
pdf_p_198.text = [];
pdf_p_198.text.push("per l'attenzione");
pdf_p_198.style = ".thanks-subtitle";
pdf_sect_196["content"].push(pdf_p_198);
pdf_sect_196.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_196);

// Make Pdf

// Build document definition
var now = new Date();
var documentDefinition = pdf_doc_1;
pdf_MainObject.sections.forEach(section => {
    section.content.forEach(contentItem => {
        documentDefinition.content.push(contentItem);
    });
    Object.assign({}, documentDefinition.styles, section.styles);
});

// Dump for test
    fs.writeFileSync(__dirname + "/presentazione_marzo_21.json", JSON.stringify(documentDefinition, null, "	"));

// Set fonts
var fonts = {
	Roboto: {
		normal: __dirname + "/fonts/Roboto-Regular.ttf",
		bold: __dirname + "/fonts/Roboto-Medium.ttf",
		italics: __dirname + "/fonts/Roboto-Italic.ttf",
		bolditalics: __dirname + "/fonts/Roboto-MediumItalic.ttf"
	}
};

// Create document
var printer = new pdfmake(fonts);
var pdfDoc = printer.createPdfKitDocument(documentDefinition);
pdfDoc.pipe(fs.createWriteStream(__dirname + "/presentazione_marzo_21.pdf"));
pdfDoc.end();
console.log("DONE written", new Date() - now)
