const fs = require("fs");
const docx = require("docx");
const convertInchesToTwip = docx.convertInchesToTwip;
const convertMillimetersToTwip = docx.convertMillimetersToTwip;

const docx_doc_1 = { sections: [], styles: [] };
const docx_sect_2 = { properties: {}, headers:{}, footers:{}, children: [] };
const docx_page_3 = {};
const docx_margin_4 = {};
docx_margin_4.top = convertInchesToTwip(1.2);
docx_margin_4.right = convertInchesToTwip(1.2);
docx_margin_4.bottom = convertInchesToTwip(1.2);
docx_margin_4.left = convertInchesToTwip(1.2);
docx_page_3.margin = docx_margin_4;
docx_sect_2.properties.page = docx_page_3;
const docx_paragraph_5 = {};
docx_paragraph_5.children = [];
docx_paragraph_5.tabStops = [];
const docx_txt_6 = {};
docx_txt_6.text = "1.";
docx_txt_6.font = "Garamond";
docx_txt_6.size = 36;
const docx_txt_6Obj = new docx.TextRun(docx_txt_6);
docx_paragraph_5.children.push(docx_txt_6Obj);
const docx_paragraph_5Obj = new docx.Paragraph(docx_paragraph_5);
docx_sect_2.children.push(docx_paragraph_5Obj);
const docx_paragraph_7 = {};
docx_paragraph_7.children = [];
docx_paragraph_7.tabStops = [];
const docx_spacing_8 = {};
docx_spacing_8.after = convertInchesToTwip(1.5);
docx_paragraph_7.spacing = docx_spacing_8;
const docx_txt_9 = {};
docx_txt_9.text = "La virtualità della durata";
docx_txt_9.font = "Garamond";
docx_txt_9.size = 36;
const docx_txt_9Obj = new docx.TextRun(docx_txt_9);
docx_paragraph_7.children.push(docx_txt_9Obj);
const docx_paragraph_7Obj = new docx.Paragraph(docx_paragraph_7);
docx_sect_2.children.push(docx_paragraph_7Obj);
const docx_paragraph_10 = {};
docx_paragraph_10.children = [];
docx_paragraph_10.tabStops = [];
docx_paragraph_10.style = "content";
const docx_txt_11 = {};
docx_txt_11.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_11.style = "content";
const docx_txt_11Obj = new docx.TextRun(docx_txt_11);
docx_paragraph_10.children.push(docx_txt_11Obj);
const docx_paragraph_10Obj = new docx.Paragraph(docx_paragraph_10);
docx_sect_2.children.push(docx_paragraph_10Obj);
docx_doc_1.sections.push(docx_sect_2)
const docx_sect_12 = { properties: {}, headers:{}, footers:{}, children: [] };
const docx_page_13 = {};
const docx_margin_14 = {};
docx_margin_14.top = convertInchesToTwip(1.2);
docx_margin_14.right = convertInchesToTwip(1.2);
docx_margin_14.bottom = convertInchesToTwip(1.2);
docx_margin_14.left = convertInchesToTwip(1.2);
docx_page_13.margin = docx_margin_14;
docx_sect_12.properties.page = docx_page_13;
const docx_header_15 = {};
docx_header_15.children = [];
const docx_paragraph_16 = {};
docx_paragraph_16.children = [];
docx_paragraph_16.tabStops = [];
const docx_border_17 = {};
const docx_bottom_18 = {};
docx_bottom_18.size = 1;
docx_bottom_18.value = "single";
docx_bottom_18.space = 2;
docx_border_17.bottom = docx_bottom_18;
docx_paragraph_16.border = docx_border_17;
const docx_txt_19 = {};
docx_txt_19.text = "La virtualità della durata";
docx_txt_19.font = "Garamond";
docx_txt_19.size = 32;
const docx_txt_19Obj = new docx.TextRun(docx_txt_19);
docx_paragraph_16.children.push(docx_txt_19Obj);
const docx_paragraph_16Obj = new docx.Paragraph(docx_paragraph_16);
docx_header_15.children.push(docx_paragraph_16Obj);
const docx_header_15Obj = new docx.Header(docx_header_15);
docx_sect_12.headers.default = docx_header_15Obj;
const docx_paragraph_20 = {};
docx_paragraph_20.children = [];
docx_paragraph_20.tabStops = [];
docx_paragraph_20.style = "content";
const docx_txt_21 = {};
docx_txt_21.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_21.style = "content";
const docx_txt_21Obj = new docx.TextRun(docx_txt_21);
docx_paragraph_20.children.push(docx_txt_21Obj);
const docx_paragraph_20Obj = new docx.Paragraph(docx_paragraph_20);
docx_sect_12.children.push(docx_paragraph_20Obj);
const docx_paragraph_22 = {};
docx_paragraph_22.children = [];
docx_paragraph_22.tabStops = [];
docx_paragraph_22.style = "content";
const docx_txt_23 = {};
docx_txt_23.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_23.style = "content";
const docx_txt_23Obj = new docx.TextRun(docx_txt_23);
docx_paragraph_22.children.push(docx_txt_23Obj);
const docx_paragraph_22Obj = new docx.Paragraph(docx_paragraph_22);
docx_sect_12.children.push(docx_paragraph_22Obj);
const docx_paragraph_24 = {};
docx_paragraph_24.children = [];
docx_paragraph_24.tabStops = [];
docx_paragraph_24.style = "content";
const docx_txt_25 = {};
docx_txt_25.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_25.style = "content";
const docx_txt_25Obj = new docx.TextRun(docx_txt_25);
docx_paragraph_24.children.push(docx_txt_25Obj);
const docx_paragraph_24Obj = new docx.Paragraph(docx_paragraph_24);
docx_sect_12.children.push(docx_paragraph_24Obj);
docx_doc_1.sections.push(docx_sect_12)
const docx_sect_26 = { properties: {}, headers:{}, footers:{}, children: [] };
const docx_page_27 = {};
const docx_margin_28 = {};
docx_margin_28.top = convertInchesToTwip(1.2);
docx_margin_28.right = convertInchesToTwip(1.2);
docx_margin_28.bottom = convertInchesToTwip(1.2);
docx_margin_28.left = convertInchesToTwip(1.2);
docx_page_27.margin = docx_margin_28;
docx_sect_26.properties.page = docx_page_27;
const docx_paragraph_29 = {};
docx_paragraph_29.children = [];
docx_paragraph_29.tabStops = [];
const docx_txt_30 = {};
docx_txt_30.text = "2.";
docx_txt_30.font = "Garamond";
docx_txt_30.size = 36;
const docx_txt_30Obj = new docx.TextRun(docx_txt_30);
docx_paragraph_29.children.push(docx_txt_30Obj);
const docx_paragraph_29Obj = new docx.Paragraph(docx_paragraph_29);
docx_sect_26.children.push(docx_paragraph_29Obj);
const docx_paragraph_31 = {};
docx_paragraph_31.children = [];
docx_paragraph_31.tabStops = [];
const docx_spacing_32 = {};
docx_spacing_32.after = convertInchesToTwip(1.5);
docx_paragraph_31.spacing = docx_spacing_32;
const docx_txt_33 = {};
docx_txt_33.text = "Spazio e tempo";
docx_txt_33.font = "Garamond";
docx_txt_33.size = 36;
const docx_txt_33Obj = new docx.TextRun(docx_txt_33);
docx_paragraph_31.children.push(docx_txt_33Obj);
const docx_paragraph_31Obj = new docx.Paragraph(docx_paragraph_31);
docx_sect_26.children.push(docx_paragraph_31Obj);
const docx_paragraph_34 = {};
docx_paragraph_34.children = [];
docx_paragraph_34.tabStops = [];
docx_paragraph_34.style = "content";
const docx_txt_35 = {};
docx_txt_35.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_35.style = "content";
const docx_txt_35Obj = new docx.TextRun(docx_txt_35);
docx_paragraph_34.children.push(docx_txt_35Obj);
const docx_paragraph_34Obj = new docx.Paragraph(docx_paragraph_34);
docx_sect_26.children.push(docx_paragraph_34Obj);
docx_doc_1.sections.push(docx_sect_26)
const docx_sect_36 = { properties: {}, headers:{}, footers:{}, children: [] };
const docx_page_37 = {};
const docx_margin_38 = {};
docx_margin_38.top = convertInchesToTwip(1.2);
docx_margin_38.right = convertInchesToTwip(1.2);
docx_margin_38.bottom = convertInchesToTwip(1.2);
docx_margin_38.left = convertInchesToTwip(1.2);
docx_page_37.margin = docx_margin_38;
docx_sect_36.properties.page = docx_page_37;
const docx_header_39 = {};
docx_header_39.children = [];
const docx_paragraph_40 = {};
docx_paragraph_40.children = [];
docx_paragraph_40.tabStops = [];
const docx_border_41 = {};
const docx_bottom_42 = {};
docx_bottom_42.size = 1;
docx_bottom_42.value = "single";
docx_bottom_42.space = 2;
docx_border_41.bottom = docx_bottom_42;
docx_paragraph_40.border = docx_border_41;
const docx_txt_43 = {};
docx_txt_43.text = "Spazio e tempo";
docx_txt_43.font = "Garamond";
docx_txt_43.size = 32;
const docx_txt_43Obj = new docx.TextRun(docx_txt_43);
docx_paragraph_40.children.push(docx_txt_43Obj);
const docx_paragraph_40Obj = new docx.Paragraph(docx_paragraph_40);
docx_header_39.children.push(docx_paragraph_40Obj);
const docx_header_39Obj = new docx.Header(docx_header_39);
docx_sect_36.headers.default = docx_header_39Obj;
const docx_paragraph_44 = {};
docx_paragraph_44.children = [];
docx_paragraph_44.tabStops = [];
docx_paragraph_44.style = "content";
const docx_txt_45 = {};
docx_txt_45.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_45.style = "content";
const docx_txt_45Obj = new docx.TextRun(docx_txt_45);
docx_paragraph_44.children.push(docx_txt_45Obj);
const docx_paragraph_44Obj = new docx.Paragraph(docx_paragraph_44);
docx_sect_36.children.push(docx_paragraph_44Obj);
const docx_paragraph_46 = {};
docx_paragraph_46.children = [];
docx_paragraph_46.tabStops = [];
docx_paragraph_46.style = "content";
const docx_txt_47 = {};
docx_txt_47.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_47.style = "content";
const docx_txt_47Obj = new docx.TextRun(docx_txt_47);
docx_paragraph_46.children.push(docx_txt_47Obj);
const docx_paragraph_46Obj = new docx.Paragraph(docx_paragraph_46);
docx_sect_36.children.push(docx_paragraph_46Obj);
const docx_paragraph_48 = {};
docx_paragraph_48.children = [];
docx_paragraph_48.tabStops = [];
docx_paragraph_48.style = "content";
const docx_txt_49 = {};
docx_txt_49.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_49.style = "content";
const docx_txt_49Obj = new docx.TextRun(docx_txt_49);
docx_paragraph_48.children.push(docx_txt_49Obj);
const docx_paragraph_48Obj = new docx.Paragraph(docx_paragraph_48);
docx_sect_36.children.push(docx_paragraph_48Obj);
const docx_paragraph_50 = {};
docx_paragraph_50.children = [];
docx_paragraph_50.tabStops = [];
docx_paragraph_50.style = "content";
const docx_txt_51 = {};
docx_txt_51.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_51.style = "content";
const docx_txt_51Obj = new docx.TextRun(docx_txt_51);
docx_paragraph_50.children.push(docx_txt_51Obj);
const docx_paragraph_50Obj = new docx.Paragraph(docx_paragraph_50);
docx_sect_36.children.push(docx_paragraph_50Obj);
const docx_paragraph_52 = {};
docx_paragraph_52.children = [];
docx_paragraph_52.tabStops = [];
docx_paragraph_52.style = "content";
const docx_txt_53 = {};
docx_txt_53.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis ex, aliquet et faucibus quis, euismod in odio. Fusce gravida tempor nunc sed lacinia. Nulla sed dolor fringilla, fermentum libero ut, egestas ex. Donec pellentesque metus non orci lacinia bibendum. Cras porta ex et mollis hendrerit. Suspendisse id lectus suscipit, elementum lacus eu, convallis felis. Fusce sed bibendum dolor, id posuere ligula. Aliquam eu elit ut urna eleifend vestibulum. Praesent condimentum at turpis sed scelerisque. Suspendisse porttitor metus nec vestibulum egestas. Sed in eros sapien. Morbi efficitur placerat est a consequat. Nunc bibendum porttitor mi nec tempus. Morbi dictum augue porttitor nisi sodales sodales.";
docx_txt_53.style = "content";
const docx_txt_53Obj = new docx.TextRun(docx_txt_53);
docx_paragraph_52.children.push(docx_txt_53Obj);
const docx_paragraph_52Obj = new docx.Paragraph(docx_paragraph_52);
docx_sect_36.children.push(docx_paragraph_52Obj);
docx_doc_1.sections.push(docx_sect_36)

const docx_MainObject = new docx.Document(docx_doc_1);

docx.Packer.toBuffer(docx_MainObject).then((buffer) => {
    fs.writeFileSync("book_lab_maggio_23.docx", buffer);
    console.log("DONE written")
});
